#config_version=6

mode:
  start_events: inline_drop_all
  stop_events: end_inline_knockall
  events_when_started: trigger_knockdown_coils
  priority: 1000

event_player:
  trigger_knockdown_coils:
    - knockdown_drop_a
    - knockdown_drop_b
    - knockdown_drop_c
    - knockdown_drop_d
    - finish_inline_knockall|250ms
  player_suspend_spot{current_player.suspend_spot==0}:
    - end_inline_knockall

variable_player:
  shot_group_drop_inline_hit{settings.in_line_scoring==0}:
    score:
      int: 0
      action: add
      block: true
    bonuscount:
      int: 0
      action: add
      block: true
  shot_group_drop_inline_hit{settings.in_line_scoring==1}:
    score:
      int: 0
      action: add
      block: true
    bonuscount:
      int: 0
      action: add
      block: true
  trigger_knockdown_coils:
    suspend_spot: 1
    suspend_chase_show: 1
  finish_inline_knockall:
    in_line_a_down:
      action: set
      int: 0
    in_line_b_down:
      action: set
      int: 0
    in_line_c_down:
      action: set
      int: 0
    in_line_d_down:
      action: set
      int: 0
    suspend_spot:
      action: set
      int: 0
    suspend_chase_show:
      action: set
      int: 0