#config_version=5

#slides:
#  _overwrite: true
#  # door open
#  service_door_open:
#  - type: text
#    text: Door Open
#    style: medium
#    y: bottom + 75%
#  - type: text
#    text: Press enter for service
#    style: small
#    y: bottom + 50%
#  # menu
#  service_menu:
#  - type: text
#    text: Outpost Kodelia Service Menu
#    style: medium
#    x: center
#    y: bottom + 80%
#  # switch test
#  service_switch_test:
#  - type: text
#    text: Switch Test
#    style: small
#    x: center
#    y: bottom + 85%
#  - type: text
#    text: "Last: (switch_num)"
#    style: small
#    y: bottom + 67%
#  - type: text
#    text: "(switch_name)"
#    style: small
#    y: bottom + 50%
#  - type: text
#    text: "(switch_label)"
#    style: small
#    y: bottom + 31%
#  - type: text
#    text: (switch_state)
#    style: small
#    y: bottom + 10%
#  # coil test
#  service_coil_test:
#  - type: text
#    text: "Coil Test - (board_name)"
#    style: small
#    x: center
#    y: bottom + 85%
#  - type: text
#    text: "(coil_name)"
#    style: small
#    y: bottom + 67%
#  - type: text
#    text: "(coil_label)"
#    style: small
#    y: bottom + 50%
#  - type: text
#    text: "(coil_num)"
#    style: small
#    y: bottom + 31%
#  # coil test
#  service_light_test:
#  - type: text
#    text: "Light Test - (board_name)"
#    style: small
#    x: center
#    y: bottom + 80%
#  - type: text
#    text: "(light_name)"
#    style: small
#    y: bottom + 60%
#  - type: text
#    text: "(light_label)"
#    style: small
#    y: bottom + 40%
#  - type: text
#    text: "(light_num)/(test_color)"
#    style: small
#    y: bottom + 20%
#  # software update
#  software_update:
#  - type: text
#    text: "Perform software update?"
#    style: small
#    x: center
#    y: bottom + 80%
#  - type: text
#    text: "(run_update)"
#    style: small
#    y: bottom + 60%
#  - type: text
#    text: "DO NOT TURN OFF POWER DURING UPDATE"
#    style: small
#    y: bottom + 40%
#    opacity: 0.5
#  # settings
#  service_settings:
#  - type: text
#    text: "Settings"
#    style: small
#    x: center
#    y: bottom + 80%
#  - type: text
#    text: "(settings_label)"
#    style: small
#    y: bottom + 60%
#  - type: text
#    text: "(value_label)"
#    style: small
#    y: bottom + 40%
#    opacity: 0.5
#  service_settings_edit:
#  - type: text
#    text: "Settings"
#    style: small
#    x: center
#    y: bottom + 80%
#  - type: text
#    text: "(settings_label)"
#    style: small
#    y: bottom + 60%
#    opacity: 0.5
#  - type: text
#    text: "(value_label)"
#    style: small
#    y: bottom + 40%
#  service_volume_changed:
#  - type: text
#    text: "Volume (machine|master_volume)"
#    style: medium
#    y: middle
#  service_options_slide:
#  - type: text
#    text: "(title)"
#    style: small
#    x: center
#    y: bottom + 80%
#  - type: text
#    text: "(question)"
#    style: small
#    y: bottom + 60%
#  - type: text
#    text: "(option)"
#    style: small
#    y: bottom + 40%
#  - type: text
#    text: "(warning)"
#    style: small
#    y: bottom + 20%
#  # switch test
