#config_version=5

mode:
  code: service.Service
  priority: 100000
  game_mode: False
  start_events: reset_complete
  stop_events: shutdown
  stop_on_ball_end: False

show_player:
  kodelia_service_menu_flash_all_lights:
    kodelia_all_lights:
      show_tokens:
        tag1: j3
        tag2: j4
        tag3: j5
        tag4: j7
        tag5: j8
        tag6: j9
        tag7: j10
        color: (test_color)
  kodelia_service_menu_flash_all_lights_stop:
    kodelia_all_lights:
      action: stop
  kodelia_service_menu_flash_channel:
    kodelia_all_lights:
      show_tokens:
        tag1: (test_channel)
        color: (test_color)
  kodelia_service_menu_flash_channel_lights_stop:
    kodelia_all_lights:
      action: stop


slide_player:
  # light test:
  service_light_all_test_start:
    service_light_all_test:
      action: play
      priority: 2
  service_light_all_test_stop:
    service_light_all_test:
      action: remove
  service_light_channel_test_start:
    service_light_channel_test:
      action: play
      priority: 2
  service_light_channel_test_stop:
    service_light_channel_test:
      action: remove

slides:
  service_light_all_test:
    - type: text
      text: "All Light Test"
      style: small
      x: center
      y: bottom + 80%
    - type: text
      text: "(test_color)"
      style: small
      y: bottom + 20%
  service_light_channel_test:
    - type: text
      text: "Channel Test"
      style: small
      x: center
      y: bottom + 80%
    - type: text
      text: "(test_channel)"
      x: center
      y: bottom + 40%
    - type: text
      text: "(test_color)"
      style: small
      y: bottom + 20%