#config_version=5

mode:
  code: service.Service
  priority: 100000
  game_mode: False
  start_events: reset_complete
  stop_events: shutdown
  stop_on_ball_end: False

show_player:
  kodelia_service_menu_flash_all_lights:
    kodelia_all_lights:
      show_tokens:
        tag1: j3
        tag2: j4
        tag3: j5
        tag4: j7
        tag5: j8
        tag6: j9
        tag7: j10
        color: (test_color)
  kodelia_service_menu_flash_all_lights_stop:
    kodelia_all_lights:
      action: stop
  kodelia_service_menu_flash_channel:
    kodelia_all_lights:
      show_tokens:
        tag1: (test_channel)
        color: (test_color)
  kodelia_service_menu_flash_channel_lights_stop:
    kodelia_all_lights:
      action: stop


slide_player:
  # light test:
  service_light_all_test_start:
    service_light_all_test:
      action: play
      priority: 2
  service_light_all_test_stop:
    service_light_all_test:
      action: remove
  service_light_channel_test_start:
    service_light_channel_test:
      action: play
      priority: 2
  service_light_channel_test_stop:
    service_light_channel_test:
      action: remove



slides:
  _overwrite: True
  service_light_all_test:
    - type: text
      text: "All Light Test"
      style: kodelia_service_small
      x: center
      y: bottom + 80%
    - type: text
      text: "(test_color)"
      style: kodelia_service_small
      y: bottom + 20%
  service_light_channel_test:
    - type: text
      text: "Channel Test"
      style: kodelia_service_small
      x: center
      y: bottom + 80%
    - type: text
      text: "(test_channel)"
      style: kodelia_service_small
      x: center
      y: bottom + 40%
    - type: text
      text: "(test_color)"
      style: kodelia_service_small
      y: bottom + 20%
  # volume changed
  service_volume_changed:
  - type: text
    text: "Volume (machine|master_volume)"
    style: kodelia_service_medium
    y: middle
  # door open
  service_door_open:
  - type: text
    text: Door Open
    style: kodelia_service_small
    y: bottom + 80%
  - type: text
    text: "Volume (machine|master_volume)"
    style: kodelia_service_small
    y: bottom + 60%
  - type: text
    text: Press enter for service
    font_name: hobby
    y: bottom + 40%

  # menu
  service_menu:
  - type: text
    text: Dukes of Hazzard Service Menu
    style: kodelia_service_big
    x: center
    y: bottom + 80%
  # confirm slide
  service_options_slide:
  - type: text
    text: "(title)"
    style: kodelia_service_small
    x: center
    y: bottom + 80%
  - type: text
    text: "(question)"
    font_name: hobby
    y: bottom + 60%
  - type: text
    text: "(option)"
    style: kodelia_service_small
    y: bottom + 40%
  - type: text
    text: "(warning)"
    style: kodelia_service_small
    y: bottom + 20%
  # switch test
  service_switch_test:
  - type: text
    text: Switch Test
    style: kodelia_service_small
    x: center
    y: bottom + 85%
  - type: text
    text: "Last: (switch_num)"
    font_name: hobby
    y: bottom + 67%
  - type: text
    text: "(switch_name)"
    style: kodelia_service_small
    y: bottom + 50%
  - type: text
    text: "(switch_label)"
    style: kodelia_service_small
    y: bottom + 31%
  - type: text
    text: (switch_state)
    style: kodelia_service_small
    y: bottom + 10%
  # coil test
  service_coil_test:
  - type: text
    text: "Coil Test - (board_name)"
    style: kodelia_service_small
    x: center
    y: bottom + 85%
  - type: text
    text: "(coil_name)"
    style: kodelia_service_small
    y: bottom + 67%
  - type: text
    text: "(coil_label)"
    style: kodelia_service_small
    y: bottom + 50%
  - type: text
    text: "(coil_num)"
    style: kodelia_service_small
    y: bottom + 31%
  # coil test
  service_light_test:
  - type: text
    text: "Light Test - (board_name)"
    style: kodelia_service_small
    x: center
    y: bottom + 80%
  - type: text
    text: "(light_name)"
    style: kodelia_service_small
    y: bottom + 60%
  - type: text
    text: "(light_label)"
    style: kodelia_service_small
    y: bottom + 40%
  - type: text
    text: "(light_num)/(test_color)"
    style: kodelia_service_small
    y: bottom + 20%
  # software update
  software_update:
  - type: text
    text: "Perform software update?"
    style: kodelia_service_small
    x: center
    y: bottom + 80%
  - type: text
    text: "(run_update)"
    style: kodelia_service_small
    y: bottom + 60%
  - type: text
    text: "DO NOT TURN OFF POWER DURING UPDATE"
    style: kodelia_service_small
    y: bottom + 40%
    opacity: 0.5
  # settings
  service_settings:
  - type: text
    text: "Settings"
    style: kodelia_service_small
    x: center
    y: bottom + 80%
  - type: text
    text: "(settings_label)"
    style: kodelia_service_small
    y: bottom + 60%
  - type: text
    text: "(value_label)"
    style: kodelia_service_small
    y: bottom + 40%
    opacity: 0.5
  service_settings_edit:
  - type: text
    text: "Settings"
    style: kodelia_service_small
    x: center
    y: bottom + 80%
  - type: text
    text: "(settings_label)"
    style: kodelia_service_small
    y: bottom + 60%
    opacity: 0.5
  - type: text
    text: "(value_label)"
    style: kodelia_service_small
    y: bottom + 40%

  service_audits_menu:
  - type: text
    text: "Audits"
    style: kodelia_service_small
    x: center
    y: bottom + 80%
  - type: text
    text: "(audits_label)"
    style: kodelia_service_small
    y: bottom + 60%
  - type: text
    text: "(value_label)"
    style: kodelia_service_small
    y: bottom + 40%

widgets:
  # power off on door open slide
  _overwrite: True
  service_power_off_door_open:
    type: text
    text: Coil Power Off
    y: bottom + 20%
    style: kodelia_service_small
    animations:
      add_to_slide:
      - property: opacity
        value: 1
        duration: 0.5s
      - property: opacity
        value: 0
        duration: 0.5s
        repeat: true
  # power off on coil test slide
  service_power_off_coil_test:
    type: text
    text: Coil Power Off
    style: kodelia_service_small
    y: bottom + 10%
    animations:
      add_to_slide:
      - property: opacity
        value: 1
        duration: 0.5s
      - property: opacity
        value: 0
        duration: 0.5s
        repeat: true

  # menu items
  service_menu_item:
    type: text
    text: (label)
    style: kodelia_service_medium
    valign: top
    halign: left
  kservice_menu_item:
    type: text
    text: (ks_last)
    style: kodelia_service_medium
    x: center
    y: bottom + 60%


widget_player:
  # power off
  _overwrite: true
  service_power_off:
    service_power_off_door_open:
      action: add
      slide: service_door_open
    service_power_off_coil_test:
      action: add
      slide: service_coil_test
  service_power_on:
    service_power_off_door_open:
      action: remove
      slide: service_door_open
    service_power_off_coil_test:
      action: remove
      slide: service_coil_test

  # menu items
  service_menu_selected:
    service_menu_item:
      action: add
      slide: service_menu
    kservice_menu_item:
      action: add
      slide: service_menu

  service_menu_deselected:
    service_menu_item:
      action: remove
      slide: service_menu
    kservice_menu_item:
      action: remove
      slide: service_menu