#config_version=5

# River Multi-ball is Ready

# EVENTS --
# multiball_chase_multiball_started
# multiball_chase_multiball_shoot_again
# multiball_chase_multiball_lost_ball
# multiball_chase_multiball_shoot_again_ended
# multiball_chase_multiball_ended

mode:
  start_events: start_mode_chase_multiball
  stop_events: multiball_chase_multiball_ended, end_chase_mode
  events_when_started: chase_notify
  priority: 200

state_machines:
  chase_notify_state:
    states:
      start:
        label: start_state
      step1:
        label: end_state
    transitions:
      - source: start
        target: step1
        events: show_chase_mball_done

event_player:
  chase_notify{device.state_machines.chase_notify_state.state == "start"}:
    show_notify_flash_text:
      text_1: "CHASE  "
      text_2: "M-BALL"
      text_3: "READY "
      text_4: "ESCAPE!"
      events_when_completed: show_chase_mball_done
  ball_hold_chase_hold_held_ball:
    - start_chase_sequence
  start_chase_sequence:
    - zzz_kick_a_ball_if_not_in_multiball
  multiball_chase_multiball_started:
    - end_chase_sequence
  balls_in_play{balls==1}:
    - release_chase_hold
    - end_chase_mode|100ms

shots:
  chase_saucer:
    switch: s_saucer_treasure_chamber

ball_holds:
  chase_hold:
    balls_to_hold: 1
    hold_devices: bd_escape_saucer
    release_one_events: zzz_start_chase_multiball, release_chase_hold
    disable_events: zzz_chase_multiball_started

ball_saves:
  pre_chase_ballsave:
    enable_events: start_chase_sequence
    disable_events: release_chase_hold
    only_last_ball: true

multiballs:
  pre_chase_multiball:
    ball_count: 1
    ball_count_type: add
    start_events: start_chase_sequence
    stop_events: end_chase_sequence
  chase_multiball:
    ball_count: 2
    ball_count_type: add
    shoot_again: settings.chase_ball_save
    start_events: chase_multiball_qualified
