#config_version=5

# EVENTS --
# multiball_chase_multiball_started
# multiball_chase_multiball_shoot_again
# multiball_chase_multiball_lost_ball
# multiball_chase_multiball_shoot_again_ended
# multiball_chase_multiball_ended

mode:
  start_events: start_mode_chase_multiball
  stop_events: boars_nest_ended, end_chase_mode, boars_nest_ended_failed
  events_when_started: chase_notify, chase_reset_general_lee_speed
  priority: 200

state_machines:
  chase_notify_state:
    states:
      start:
        label: start_state
      step1:
        label: end_state
    transitions:
      - source: start
        target: step1
        events: show_chase_mball_done

event_player:
  chase_notify{device.state_machines.chase_notify_state.state == "start"}:
    show_notify_flash_text:
      text_1: "CHASE  "
      text_2: "M-BALL"
      text_3: "READY "
      text_4: "ESCAPE!"
      events_when_completed: show_chase_mball_done
  start_chase_sequence:
    - drops_inline_reset
    - bonus_multiply_5x
    - disable_two_ball_multiball_progress
#  This is now thrown from the escape saucer mode
#  ball_hold_chase_hold_held_ball{current_player.boars_nest_active==0}:
#    - start_chase_sequence
#  balls_in_play{balls==1 and current_player.boars_nest_active==0}:
  multiball_pre_chase_multiball_ended{current_player.boars_nest_active==0}:
    - release_chase_hold
    - end_chase_mode|100ms
  tilt{current_player.boars_nest_active==0}:
    - end_chase_mode
  gc_start_mball_hit{current_player.general_lee_speed>=120}:
    - end_chase_sequence
    - chase_multiball_qualified
  hz_start_mball_hit{current_player.general_lee_speed>=120}:
    - end_chase_sequence
    - chase_multiball_qualified
  chase_multiball_qualified:
    - start_chase_multiball
  gc_start_mball_hit{current_player.general_lee_speed<120}:
    - general_lee_speed_add_5
    - boars_nest_early_creek_entry
  hz_start_mball_hit{current_player.general_lee_speed<120}:
    - general_lee_speed_add_5
    - boars_nest_early_hazzard_entry
  release_chase_hold:
    - escape_saucer_eject
    - end_chase_shows_fail
    - enable_two_ball_multiball_progress
    - next_song
  start_chase_multiball:
    - escape_saucer_eject
#TODO - make more various switches add speed values
  sw_kpf:
    - general_lee_speed_add_1
  kodelia_tilt:
    - end_chase_shows_fail
    - end_chase_mode

shots:
  gc_start_mball:
    switch: s_saucer_golden_cliffs
    enable_events: chase_notify
    disable_events: release_chase_hold, end_chase_sequence
  hz_start_mball:
    switch: s_saucer_paragon
    enable_events: chase_notify
    disable_events: release_chase_hold, end_chase_sequence

multiballs:
  pre_chase_multiball:
    add_a_ball_events: start_chase_multiball
    ball_count: 1
    ball_count_type: add
    start_events: start_chase_sequence
    stop_events: escape_saucer_boars_nest_collect
    shoot_again: 0s

variable_player:
  chase_reset_general_lee_speed:
      general_lee_speed:
        action: set
        int: 0
      boars_nest_active:
        action: set
        int: 0
  start_chase_sequence:
      in_line_a_down:
        action: set
        int: 0
      in_line_b_down:
        action: set
        int: 0
      in_line_c_down:
        action: set
        int: 0
      in_line_d_down:
        action: set
        int: 0
  multiball_pre_chase_multiball_started:
      general_lee_speed:
        action: set
        int: 40
  general_lee_speed_add_1{current_player.boars_nest_active!=1 and current_player.general_lee_speed>0}:
      general_lee_speed:
        # temp change to 10 to make testing easier
        int: 10
  general_lee_speed_add_3{current_player.boars_nest_active!=1 and current_player.general_lee_speed>0}:
      general_lee_speed:
        int: 3
  general_lee_speed_add_5{current_player.boars_nest_active!=1 and current_player.general_lee_speed>0}:
      general_lee_speed:
        int: 5

segment_display_player:
  multiball_display_creek{device.multiballs.creek_multiball.balls_live_target>0}:
    display1:
      action: remove
      key: chase_1
    display2:
      action: remove
      key: chase_2
    display3:
      action: remove
      key: chase_3
    display4:
      action: remove
      key: chase_4
  multiball_display_hazzard{device.multiballs.creek_multiball.balls_live_target>0}:
    display1:
      action: remove
      key: chase_1
    display2:
      action: remove
      key: chase_2
    display3:
      action: remove
      key: chase_3
    display4:
      action: remove
      key: chase_4
  multiball_display_boar{current_player.boars_nest_active>0}:
    display1:
      action: remove
      key: chase_1
    display2:
      action: remove
      key: chase_2
    display3:
      action: remove
      key: chase_3
    display4:
      action: remove
      key: chase_4

  multiball_display_chase{device.multiballs.pre_chase_multiball.balls_live_target>0 and current_player.general_lee_speed<120}:
    display1:
      action: add
      key: chase_1
      priority: 400
      text: "Player{current_player.number}"
    display2:
      action: add
      key: chase_2
      priority: 400
      text: "{current_player.score:d}"
    display3:
      action: add
      key: chase_3
      priority: 400
      text: "SpeedUp"
    display4:
      action: add
      key: chase_4
      priority: 400
      text: "MPH {current_player.general_lee_speed:d}"
  multiball_display_chase{device.multiballs.pre_chase_multiball.balls_live_target>0 and current_player.general_lee_speed>=120}:
    display1:
      action: add
      key: chase_1
      priority: 400
      text: "Player{current_player.number}"
    display2:
      action: add
      key: chase_2
      priority: 400
      text: "{current_player.score:d}"
    display3:
      action: add
      key: chase_3
      priority: 400
      text: "ESCAPE"
    display4:
      action: add
      key: chase_4
      priority: 400
      text: "ROSCOE!"

sound_player:
  start_chase_sequence_audio:
    gameplay_music:
      action: stop
      fade_out: 500ms
    duck_on_a_junebug:
      action: stop
    hot_pursuit:
      action: play
      loops: 0
      events_when_about_to_finish: play_horn
      about_to_finish_time: 50ms
  play_horn:
    dixie_horn:
      action: play
      loops: 0
      events_when_about_to_finish:
        - start_chase_theme
        - start_siren
        - start_chase_sequence
        - start_yeehaw
      about_to_finish_time: 50ms
  start_chase_theme:
    chase_theme:
      delay: 500ms
      action: play
      loops: -1
  start_siren:
    police_siren:
      delay: 500ms
      action: play
      loops: -1
  end_chase_shows_fail:
    chase_theme:
      action: stop
      fade_out: 500ms
    police_siren:
      action: stop
      fade_out: 500ms
  start_yeehaw:
    yee_haw:
      action: play
      loops: 0

show_player:
  start_chase_theme:
    red_siren_show:
      key: red_siren
      action: play
      speed: 60
      loops: -1
      priority: 10
    blue_siren_show:
      key: blue_siren
      action: play
      speed: 60
      loops: -1
      priority: 10
    mid_pop_dim_show:
      key: mid_pop_dim
      action: play
      loops: -1
      priority: 10
    gi_dim_show:
      key: gi_dim
      action: play
      loops: -1
      priority: 10
  start_chase_multiball:
    red_siren: stop
    blue_siren: stop
    mid_pop_dim: stop
    gi_dim: stop
  end_chase_shows_fail:
    red_siren: stop
    blue_siren: stop
    mid_pop_dim: stop
    gi_dim: stop
  play_horn:
    dixie_horn_show:
      action: play
      speed: 1
      loops: 12
      priority: 10000
  chase_notify:
    chase_start_ready_show:
      key: chase_ready_show_key
      speed: 2
      loops: -1
  start_chase_sequence:
    chase_ready_show_key:
      action: stop
