#config_version=5

# EVENTS --
# multiball_chase_multiball_started
# multiball_chase_multiball_shoot_again
# multiball_chase_multiball_lost_ball
# multiball_chase_multiball_shoot_again_ended
# multiball_chase_multiball_ended

mode:
  start_events: start_mode_chase_multiball
  stop_events: boars_nest_ended, end_chase_mode
  events_when_started: chase_notify
  priority: 200

state_machines:
  chase_notify_state:
    states:
      start:
        label: start_state
      step1:
        label: end_state
    transitions:
      - source: start
        target: step1
        events: show_chase_mball_done

event_player:
  chase_notify{device.state_machines.chase_notify_state.state == "start"}:
    show_notify_flash_text:
      text_1: "CHASE  "
      text_2: "M-BALL"
      text_3: "READY "
      text_4: "ESCAPE!"
      events_when_completed: show_chase_mball_done
  start_chase_sequence:
    - drops_inline_reset
    - bonus_multiply_5x
  ball_hold_chase_hold_held_ball:
    - start_chase_sequence
  balls_in_play{balls==1}:
    - release_chase_hold
    - end_chase_mode|100ms
  gc_start_mball_hit{current_player.general_lee_speed>=120}:
    - end_chase_sequence
    - chase_multiball_qualified
  hz_start_mball_hit{current_player.general_lee_speed>=120}:
    - end_chase_sequence
    - chase_multiball_qualified
  chase_multiball_qualified:
    - start_chase_multiball
#TODO - make more various switches add speed values
  sw_kpf:
    - general_lee_speed_add_1
  gc_start_mball_hit{current_player.general_lee_speed<120}:
    - general_lee_speed_add_5
  hz_start_mball_hit{current_player.general_lee_speed<120}:
    - general_lee_speed_add_5

shots:
  chase_saucer:
    switch: s_saucer_treasure_chamber
  gc_start_mball:
    switch: s_saucer_golden_cliffs
  hz_start_mball:
    switch: s_saucer_paragon

ball_holds:
  chase_hold:
    balls_to_hold: 1
    hold_devices: bd_escape_saucer
    release_one_events: multiball_chase_multiball_started, release_chase_hold
    disable_events: multiball_chase_multiball_started

ball_saves:
  pre_chase_ballsave:
    enable_events: start_chase_sequence
    disable_events: release_chase_hold
    only_last_ball: true

multiballs:
  pre_chase_multiball:
    ball_count: 1
    ball_count_type: add
    start_events: start_chase_sequence
    stop_events: end_chase_sequence
  chase_multiball:
    ball_count: 2
    ball_count_type: add
#    ball_locks: bd_escape_saucer
    start_events: start_chase_multiball
    stop_events: ball_save_ball_save_boars_nest_timer_start

variable_player:
  start_chase_sequence:
      in_line_a_down:
        action: set
        int: 0
      in_line_b_down:
        action: set
        int: 0
      in_line_c_down:
        action: set
        int: 0
      in_line_d_down:
        action: set
        int: 0
      general_lee_speed:
        action: set
        int: 40
      boars_nest_active:
        action: set
        int: 0
  general_lee_speed_add_1{current_player.boars_nest_active!=1}:
      general_lee_speed:
        int: 1
  general_lee_speed_add_3{current_player.boars_nest_active!=1}:
      general_lee_speed:
        int: 3
  general_lee_speed_add_5{current_player.boars_nest_active!=1}:
      general_lee_speed:
        int: 5

segment_display_player:
  multiball_display_creek{device.multiballs.creek_multiball.balls_live_target>0}:
    display1:
      action: remove
      key: chase_1
    display2:
      action: remove
      key: chase_2
    display3:
      action: remove
      key: chase_3
    display4:
      action: remove
      key: chase_4
  multiball_display_hazzard{device.multiballs.creek_multiball.balls_live_target>0}:
    display1:
      action: remove
      key: chase_1
    display2:
      action: remove
      key: chase_2
    display3:
      action: remove
      key: chase_3
    display4:
      action: remove
      key: chase_4
  multiball_display_boar{current_player.boars_nest_active>0}:
    display1:
      action: remove
      key: chase_1
    display2:
      action: remove
      key: chase_2
    display3:
      action: remove
      key: chase_3
    display4:
      action: remove
      key: chase_4

  multiball_display_chase{device.multiballs.pre_chase_multiball.balls_live_target>0 and current_player.general_lee_speed<120}:
    display1:
      action: add
      key: chase_1
      priority: 400
      text: "Player{current_player.number}"
    display2:
      action: add
      key: chase_2
      priority: 400
      text: "{current_player.score:d}"
    display3:
      action: add
      key: chase_3
      priority: 400
      text: "SpeedUp"
    display4:
      action: add
      key: chase_4
      priority: 400
      text: "MPH {current_player.general_lee_speed:d}"
  multiball_display_chase{device.multiballs.pre_chase_multiball.balls_live_target>0 and current_player.general_lee_speed>=120}:
    display1:
      action: add
      key: chase_1
      priority: 400
      text: "Player{current_player.number}"
    display2:
      action: add
      key: chase_2
      priority: 400
      text: "{current_player.score:d}"
    display3:
      action: add
      key: chase_3
      priority: 400
      text: "ESCAPE"
    display4:
      action: add
      key: chase_4
      priority: 400
      text: "ROSCOE!"
