#config_version=5

# Contains configuration data for the HAZZARD (Paragon) Saucer

#TODO "lit" priority set over "flash" (done, need to test)

# DISABLE when mode chase_multiball starts
# ENABLE when boars nest is ended

# When we add a ball hold here to award hazzard lights :
# also need to release the ball on event "boars_nest_early_hazzard_entry"

# Mode Start happens when ball starts
# Possible States: Multiball ready from previous ball, Multiball not yet ready
#
# Other possible states:
# Started Chase Sequence -- reset, disable progress
# Chase Sequence Ends (Fail)  -- enable progress
# Boars Nest Ends (Fail) -- enable progress
# Boars Nest Ends (Pass) -- enable progress

mode:
  start_events: ball_started
  events_when_started: hazzard_enable_ach
  priority: 140

achievements:
  sau_1_complete:
    show_tokens:
      leds: l_paragon_center_01p, l_paragon_center_01p2, l_paragon_saucer_01p
    show_when_completed: on
    start_events: mode_hazzard_started, enable_two_ball_multiball_progress, hazzard_ach_init
    complete_events: hazzard_saucer_sau_1_hit, spot_sau_1
    disable_events: force_hazzard_reset
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach
    reset_events: special_scored_hazzard, disable_two_ball_multiball_progress, hazzard_ach_reset
  sau_2_complete:
    show_tokens:
      leds: l_paragon_center_02a, l_paragon_center_02a2, l_paragon_saucer_02a
    show_when_completed: on
    start_events: mode_hazzard_started, enable_two_ball_multiball_progress, hazzard_ach_init
    complete_events: hazzard_saucer_sau_2_hit, spot_sau_2
    disable_events: force_hazzard_reset
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach
    reset_events: special_scored_hazzard, disable_two_ball_multiball_progress, hazzard_ach_reset
  sau_3_complete:
    show_tokens:
      leds: l_paragon_center_03r, l_paragon_center_03r2, l_paragon_saucer_03r
    show_when_completed: on
    start_events: mode_hazzard_started, enable_two_ball_multiball_progress, hazzard_ach_init
    complete_events: hazzard_saucer_sau_3_hit, spot_sau_3
    disable_events: force_hazzard_reset
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach
    reset_events: special_scored_hazzard, disable_two_ball_multiball_progress, hazzard_ach_reset
  sau_4_complete:
    show_tokens:
      leds: l_paragon_center_04a, l_paragon_center_04a2, l_paragon_saucer_04a
    show_when_completed: on
    start_events: mode_hazzard_started, enable_two_ball_multiball_progress, hazzard_ach_init
    complete_events: hazzard_saucer_sau_4_hit, spot_sau_4
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach
    disable_events: force_hazzard_reset
    reset_events: special_scored_hazzard, disable_two_ball_multiball_progress, hazzard_ach_reset
  sau_5_complete:
    show_tokens:
      leds: l_paragon_center_05g, l_paragon_center_05g2, l_paragon_saucer_05g
    show_when_completed: on
    start_events: mode_hazzard_started, enable_two_ball_multiball_progress, hazzard_ach_init
    complete_events: hazzard_saucer_sau_5_hit, spot_sau_5
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach
    disable_events: force_hazzard_reset
    reset_events: special_scored_hazzard, disable_two_ball_multiball_progress, hazzard_ach_reset
  sau_6_complete:
    show_tokens:
      leds: l_paragon_center_06o, l_paragon_center_06o2, l_paragon_saucer_06o
    show_when_completed: on
    start_events: mode_hazzard_started, enable_two_ball_multiball_progress, hazzard_ach_init
    complete_events: hazzard_saucer_sau_6_hit, spot_sau_6
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach
    disable_events: force_hazzard_reset
    reset_events: special_scored_hazzard, disable_two_ball_multiball_progress, hazzard_ach_reset
  sau_7_complete:
    show_tokens:
      leds: l_paragon_center_07n, l_paragon_center_07n2, l_paragon_saucer_07n
    show_when_completed: on
    start_events: mode_hazzard_started, enable_two_ball_multiball_progress, hazzard_ach_init
    complete_events: hazzard_saucer_sau_7_hit, spot_sau_7
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach
    disable_events: force_hazzard_reset
    reset_events: special_scored_hazzard, disable_two_ball_multiball_progress, hazzard_ach_reset

achievement_groups:
  saucer_group:
    achievements: sau_1_complete, sau_2_complete, sau_3_complete, sau_4_complete, sau_5_complete, sau_6_complete, sau_7_complete
    enable_events: enable_two_ball_multiball_progress, hazzard_enable_ach, hazzard_ach_init
    disable_events: force_hazzard_reset, hazzard_ach_reset
#    reset_events: disable_two_ball_multiball_progress
    events_when_all_completed: enable_saucer_special

shot_profiles:
  hazzard_sweep:
    advance_on_hit: false
    loop: true
    states:
      - name: sau_1
        priority: 100
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_01p
      - name: sau_2
        priority: 100
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_02a
      - name: sau_3
        priority: 100
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_03r
      - name: sau_4
        priority: 100
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_04a
      - name: sau_5
        priority: 100
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_05g
      - name: sau_6
        priority: 100
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_06o
      - name: sau_7
        priority: 100
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_07n
  hazzard_special:
    advance_on_hit: false
    states:
      - name: enabled
        show: flash_leds
        show_tokens:
          leds: l_paragon_saucer_special


# The HAZZARD saucer should be enabled to spot HAZZARD letters in the following conditions
# Normal, Single Ball Play, HAZZARD not yet completed
# Creek Multiball in progress, HAZZARD not yet completed
# The HAZZARD saucer should be disabled to spot HAZZARD letters in the following conditions
# Chase Multiball/Boars Nest mode(s) are running

shots:
  hazzard_saucer:
    switch: s_saucer_paragon
    profile: hazzard_sweep
    advance_events:
      - hazzard_select_rotate
      - hazzard_saucer_hazzard_sweep_hit{settings.hazzard_scan==1}
      - spot_hazzard_letter{settings.hazzard_scan==1}
    reset_events: special_scored_hazzard, boars_nest_ended, end_chase_mode, disable_two_ball_multiball_progress
    enable_events: special_scored_hazzard, mode_hazzard_started, multiball_hazzard_multiball_ended, enable_base_hazzard_shot, enable_two_ball_multiball_progress
    disable_events: enable_saucer_special, disable_base_hazzard_shot, force_hazzard_reset

# This applies to PARAGON RULES ONLY
  hazzard_saucer_special:
    enable_events: enable_saucer_special{settings.hazzard_multiball_feature==0}
    disable_events: special_scored_hazzard
    switch: s_saucer_paragon
    profile: hazzard_special

event_player:
  enable_saucer_special:
    - start_mode_hazzard_multiball{settings.hazzard_multiball_feature==1 and current_player.boars_nest_active!=1}
    - show_hazzard_multiball_notify{settings.hazzard_multiball_feature==1 and current_player.boars_nest_active!=1}|200ms
  mode_hazzard_started:
    - hazzard_sel_letter_1
  timer_hazzard_rotate_timer_tick:
    - hazzard_select_rotate
  hazzard_saucer_special_enabled_hit:
    - special_scored_hazzard
  special_scored_hazzard:
    - mode_hazzard_started|100ms
  disable_two_ball_multiball_progress:
    - force_hazzard_reset

# This block will spot the next unlit hazzard letter when spot_hazzard_letter is thrown
# and player is not in boars nest mode
  spot_hazzard_letter{current_player.boars_nest_active!=1}:
    - sau_1_result_(device.achievements.sau_1_complete.state)
  sau_1_result_started:
    - spot_sau_1
  sau_1_result_completed:
    - sau_2_result_(device.achievements.sau_2_complete.state)
  sau_2_result_started:
    - spot_sau_2
  sau_2_result_completed:
    - sau_3_result_(device.achievements.sau_3_complete.state)
  sau_3_result_started:
    - spot_sau_3
  sau_3_result_completed:
    - sau_4_result_(device.achievements.sau_4_complete.state)
  sau_4_result_started:
    - spot_sau_4
  sau_4_result_completed:
    - sau_5_result_(device.achievements.sau_5_complete.state)
  sau_5_result_started:
    - spot_sau_5
  sau_5_result_completed:
    - sau_6_result_(device.achievements.sau_6_complete.state)
  sau_6_result_started:
    - spot_sau_6
  sau_6_result_completed:
    - sau_7_result_(device.achievements.sau_7_complete.state)
  sau_7_result_started:
    - spot_sau_7
# Attempt to prevent ball from not ejecting if entering saucer as multiball ends
  special_scored_hazzard{device.switches.s_saucer_paragon.state==1}:
    - force_paragon_eject
  mode_hazzard_started{device.switches.s_saucer_paragon.state==1}:
    - force_paragon_eject
  multiball_hazzard_multiball_ended{device.switches.s_saucer_paragon.state==1}:
    - force_paragon_eject
  enable_base_hazzard_shot{device.switches.s_saucer_paragon.state==1}:
    - force_paragon_eject
  enable_two_ball_multiball_progress{device.switches.s_saucer_paragon.state==1}:
    - force_paragon_eject



timers:
  hazzard_rotate_timer:
    tick_interval: 3s
    control_events:
      - action: start
        event: mode_hazzard_started{settings.hazzard_scan==0}

variable_player:
  hazzard_saucer_hazzard_sweep_hit{settings.hazzard_scoring==0}:
    score: 500
    bonuscount: 1
  hazzard_saucer_hazzard_sweep_hit{settings.hazzard_scoring==1}:
    score: 3000
    bonuscount: 2
  multiball_hazzard_multiball_ended:
    hazzard_jackpot_count:
      action: set
      int: 0

sound_player:
  player_shot_hazzard_saucer:
    single_rev:
      action: play
      loops: 0
