#config_version=5

event_player:
  mode_attract_started:
    start_loop:

segment_display_player:
  mode_attract_started:
    display1:
      action: set_color
      color: "FFA500"
    display2:
      action: set_color
      color: "FFA500"
    display3:
      action: set_color
      color: "FFA500"
    display4:
      action: set_color
      color: "FFA500"
  #    color: "776300"
    display5:
      action: set_color
      color: "FFA500"
  start_loop:
    display1:
      text: "THE    "
    display2:
      text: "  DUKES"
    display3:
      text: "OF     "
    display4:
      text: "HAZZARD"
  attract_show_1_complete:
    display1:
      text: "Change"
    display2:
      text: "Text"
    display3:
      text: "*******"
    display4:
      text: "   TEST"
    display5:
      text: "__**_**"
  attract_show_2_complete:
    display1:
      text: "Theme"
    display2:
      text: "By"
    display3:
      text: "Jake"
    display4:
      text: "Danzig"
    display5:
      text: "__**_**"
  attract_show_3_complete:
    display1:
      text: "CODE   "
    display2:
      text: "BY"
    display3:
      text: "OUTPOST"
    display4:
      text: "KODELIA"
    display5:
      text: "__**_**"
#    dimDisplay4:
  attract_show_4_complete:
    display1:
      text: "This"
    display2:
      text: "Is"
    display3:
      text: "The"
    display4:
      text: "End"
    display5:
      text: "__**_**"


show_player:
   start_loop:
     attract_show_1:
       action: play
       loops: 0
       events_when_completed: attract_show_1_complete
   attract_show_1_complete:
     attract_show_2:
       action: play
       loops: 0
       events_when_completed: attract_show_2_complete
   attract_show_2_complete:
     attract_show_3:
       action: play
       loops: 0
       events_when_completed: attract_show_3_complete
   attract_show_3_complete:
     attract_show_4:
       action: play
       loops: 0
       events_when_completed: attract_show_4_complete, start_loop

shows:
   attract_show_1:
     - duration: 5
   attract_show_2:
     - duration: 5
   attract_show_3:
     - duration: 5
   attract_show_4:
     - duration: 5


#variable_player:
#  mode_attract_started|5000ms:
#    machine.display1: "test"


#show_player:
#   mode_attract_started:
#      display_segment_displays:
#        priority: 10
#
#widget_player:
#   mode_attract_started: backglass
#
#shows:
#   display_segment_displays:
#     - time: 0
#       slides:
#          segment_displaysx:
#            widgets:
#              - type: text
#                text: "DukesOf"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 420
#                y: 624
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "Hazzard"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 624
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "Outpost"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 420
#                y: 224
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "Kodelia"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 224
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "__00_00"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 424
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2

