#config_version=5

event_player:
  mode_attract_started:
    restart_loop:
    disable_playfield_coils:
    attract_sound_restart:
  restart_loop:
    start_loop:
    attract_lightshow_start:
    title_card:
  start_loop{device.switches.s_saucer_treasure_chamber.state==1}:
    - escape_saucer_eject
  flipper_cancel:
    - attract_show_last_game_scores_override
  s_flipper_left_active:
    - attract_single_flipper
  s_flipper_right_active:
    - attract_single_flipper
  attract_single_flipper:
    - attract_sound_check
  attract_sound_check{settings.attract_flipper_sound_permitted==1 and device.timers.attract_sound_cooldown.running==False}:
    - attract_cooldown_start
  timer_attract_sound_player_complete:
    - attract_cooldown_start
    - attract_sound_restart

timers:
   attract_sound_cooldown:
      start_value: 0
      end_value: 30
      direction: up
      control_events:
          - event: attract_cooldown_start
            action: restart
      start_running: false
   attract_sound_player:
      start_value: 0
      end_value: settings.attract_sound_freq
      direction: up
      control_events:
          - event: attract_cooldown_start
            action: restart
          - event: attract_sound_restart
            action: restart

sound_player:
   timer_attract_sound_cooldown_started: attract_voice

segment_display_player:
  title_card:
    display1:
      text: "THE    "
    display2:
      text: "  DUKES"
    display3:
      text: "OF     "
    display4:
      text: "HAZZARD"
  attract_show_1_complete:
    display1:
      text: "Theme"
    display2:
      text: "By"
    display3:
      text: "Jake"
    display4:
      text: "Danzig"
    display5:
      text: "       "
  attract_show_2_complete:
    display1:
      text: "CODE   "
    display2:
      text: "BY"
    display3:
      text: "OUTPOST"
    display4:
      text: "KODELIA"
    display5:
      text: "       "
  attract_show_3_complete:
    display1:
      text: "BUILT  "
    display2:
      text: "BY"
    display3:
      text: "OUTPOST"
    display4:
      text: "KODELIA"
    display5:
      text: "       "
  attract_show_4_complete:
    display1:
      text: "ARTWORK"
    display2:
      text: "BY"
    display3:
      text: "MAD"
    display4:
      text: "VOODOO"
    display5:
      text: "       "
  attract_show_last_game_scores_override:
    display1:
      action: add
      key: atr_ovr
      priority: 10000
      text: "{machine.player1_score:d}"
  lastgame_player2_o:
    display2:
      action: add
      key: atr_ovr
      priority: 10000
      text: "{machine.player2_score:d}"
  lastgame_player3_o:
    display3:
      action: add
      key: atr_ovr
      priority: 10000
      text: "{machine.player3_score:d}"
  lastgame_player4_o:
    display4:
      action: add
      key: atr_ovr
      priority: 10000
      text: "{machine.player4_score:d}"
  lastgame_player2_blank_o:
    display2:
      action: add
      key: atr_ovr
      priority: 10000
      text: "       "
  lastgame_player3_blank_o:
    display3:
      action: add
      key: atr_ovr
      priority: 10000
      text: "       "
  lastgame_player4_blank_o:
    display4:
      action: add
      key: atr_ovr
      priority: 10000
      text: "       "
  attract_show_last_game_scores_override_complete:
    display1:
      key: atr_ovr
      action: remove
    display2:
      key: atr_ovr
      action: remove
    display3:
      key: atr_ovr
      action: remove
    display4:
      key: atr_ovr
      action: remove

  attract_previous_scores:
    display1:
      text: "{machine.player1_score:d}"
  lastgame_player2:
    display2:
      text: "{machine.player2_score:d}"
  lastgame_player3:
    display3:
      text: "{machine.player3_score:d}"
  lastgame_player4:
    display4:
      text: "{machine.player4_score:d}"
  lastgame_player2_blank:
    display2:
      text: "       "
  lastgame_player3_blank:
    display3:
      text: "       "
  lastgame_player4_blank:
    display4:
      text: "       "
  attract_high_scores_1:
    display1:
      text: "GRAND"
    display2:
      text: "  CHAMP"
    display3:
      text: "{machine.score1_name}"
    display4:
      text: "{machine.score1_value}"
  attract_high_scores_2:
    display1:
      text: "1ST"
    display2:
      text: "HiSCORE"
    display3:
      text: "{machine.score2_name}"
    display4:
      text: "{machine.score2_value}"
  attract_high_scores_3:
    display1:
      text: "2ND"
    display2:
      text: "HiSCORE"
    display3:
      text: "{machine.score3_name}"
    display4:
      text: "{machine.score3_value}"
  attract_high_scores_4:
    display1:
      text: "3RD"
    display2:
      text: "HiSCORE"
    display3:
      text: "{machine.score4_name}"
    display4:
      text: "{machine.score4_value}"
  attract_high_scores_5:
    display1:
      text: "4TH"
    display2:
      text: "HiSCORE"
    display3:
      text: "{machine.score5_name}"
    display4:
      text: "{machine.score5_value}"
  kill_full_light_show:
    display1:
      text: ""
    display2:
      text: ""
    display3:
      text: ""
    display4:
      text: ""

random_event_player:
  tutorial_start:
    scope: machine
    events:
      - tutorial_creek
      - tutorial_hazzard
    force_all: true

show_player:
  attract_lightshow_start:
    gi_dim_show_key:
      action: stop
    gi:
      key: gi_show
      priority: 1
      show_tokens:
        tag1: gi
        color1: white
        tag2: pop_cores
        color2: ff7500
    characters_show:
      key: characters_show
      priority: 1
    multipliers_show:
      key: multipliers_show
      priority: 1
    super_bonus_show:
      key: super_bonus_show
      priority: 1
    bonus_show:
      key: bonus_show
      priority: 1
    spinner_show:
      key: spinner_show
      priority: 1
    escape_show:
      key: escape_show
      priority: 1
    drops_show:
      key: drops_show
      priority: 1
    oil_slick_show:
      key: oil_slick_show
      priority: 1
    creek_show:
      key: creek_show
      priority: 1
    hazzard_show:
      key: hazzard_show
      priority: 1
    hazzard_special_show:
      key: hazzard_special_show
      priority: 1
    coin_lights_show:
      key: coin_lights_show_key
      priority: 1
    red_siren_show:
      key: red_siren_show_key
      action: play
      speed: 60
      loops: 6
      priority: 10
    blue_siren_show:
      key: blue_siren_show_key
      action: play
      speed: 60
      loops: 6
      priority: 10
    high_score_show:
      key: high_score_show_key
      action: play
      loops: -1
    attract_show_1:
      action: play
      loops: 0
      events_when_stopped: attract_show_1_complete
  attract_show_1_complete:
    attract_show_2:
      action: play
      loops: 0
      events_when_stopped: attract_show_2_complete
  attract_show_2_complete:
    attract_show_3:
      action: play
      loops: 0
      events_when_stopped: attract_show_3_complete
  attract_show_3_complete:
    attract_show_4:
      action: play
      loops: 0
      events_when_stopped: attract_show_4_complete
  attract_show_4_complete:
    attract_show_5:
      action: play
      loops: 0
      events_when_stopped: attract_show_5_complete, attract_previous_scores
  attract_previous_scores:
    prev_scores:
      action: play
      loops: 0
      events_when_stopped: prev_scores_complete, attract_high_scores_1
  prev_scores_complete:
    attract_hs1:
      action: play
      loops: 0
      events_when_stopped: attract_high_scores_2
  attract_high_scores_2:
    attract_hs2:
      action: play
      loops: 0
      events_when_stopped: attract_high_scores_3
  attract_high_scores_3:
    attract_hs3:
      action: play
      loops: 0
      events_when_stopped: attract_high_scores_4
  attract_high_scores_4:
    attract_hs4:
      action: play
      loops: 0
      events_when_stopped: attract_high_scores_5
  attract_high_scores_5:
    attract_hs5:
      action: play
      loops: 0
      events_when_stopped: tutorial_start, kill_full_light_show, high_scores_complete #, restart_loop
  tutorial_creek:
    z_tutorial_creek_multiball:
      action: play
      loops: 0
      events_when_stopped: restart_loop
  tutorial_hazzard:
    z_tutorial_hazzard_multiball:
      action: play
      loops: 0
      events_when_stopped: restart_loop

  attract_show_last_game_scores_override:
    prev_scores_o:
      action: play
      loops: 0
      priority: 1000
      events_when_stopped: attract_show_last_game_scores_override_complete

  attract_single_flipper:
    attract_show_1:
      action: stop
    attract_show_2:
      action: stop
    attract_show_3:
      action: stop
    attract_show_4:
      action: stop
    attract_show_5:
      action: stop
    prev_scores:
      action: stop
    attract_hs1:
      action: stop
    attract_hs2:
      action: stop
    attract_hs3:
      action: stop
    attract_hs4:
      action: stop
    attract_hs5:
      action: stop
    z_tutorial_creek_multiball:
      action: stop
    z_tutorial_hazzard_multiball:
      action: stop

  kill_full_light_show:
    characters_show:
      action: stop
    multipliers_show:
      action: stop
    super_bonus_show:
      action: stop
    bonus_show:
      action: stop
    spinner_show:
      action: stop
    escape_show:
      action: stop
    drops_show:
      action: stop
    oil_slick_show:
      action: stop
    creek_show:
      action: stop
    hazzard_show:
      action: stop
    hazzard_special_show:
      action: stop
    red_siren_show_key:
      action: stop
    blue_siren_show_key:
      action: stop
    gi_dim_show:
      key: gi_dim_show_key
      action: play
      priority: 5000



shows:
  attract_show_1:
    - duration: 5
  attract_show_2:
    - duration: 5
  attract_show_3:
    - duration: 5
  attract_show_4:
    - duration: 5
  attract_show_5:
    - duration: 5
  prev_scores:
    - duration: 5
  prev_scores_o:
    - duration: 5
  attract_hs1:
    - duration: 5
  attract_hs2:
    - duration: 5
  attract_hs3:
    - duration: 5
  attract_hs4:
    - duration: 5
  attract_hs5:
    - duration: 5

