#config_version=5

event_player:
  mode_attract_started:
    start_loop:
  start_loop{device.switches.s_saucer_treasure_chamber.state==1}:
    - escape_saucer_eject
  start_loop:
    - disable_playfield_coils
  flipper_cancel:
    - attract_show_last_game_scores

segment_display_player:
#  mode_attract_started:
#    display1:
#      action: set_color
#      color: "FFA500"
#    display2:
#      action: set_color
#      color: "FFA500"
#    display3:
#      action: set_color
#      color: "FFA500"
#    display4:
#      action: set_color
#      color: "FFA500"
#  #    color: "776300"
#    display5:
#      action: set_color
#      color: "FFA500"
  start_loop:
    display1:
      text: "THE    "
    display2:
      text: "  DUKES"
    display3:
      text: "OF     "
    display4:
      text: "HAZZARD"
  attract_show_1_complete:
    display1:
      text: "Change"
    display2:
      text: "Text"
    display3:
      text: "*******"
    display4:
      text: "   TEST"
    display5:
      text: "__**_**"
  attract_show_2_complete:
    display1:
      text: "Theme"
    display2:
      text: "By"
    display3:
      text: "Jake"
    display4:
      text: "Danzig"
    display5:
      text: "__**_**"
  attract_show_3_complete:
    display1:
      text: "CODE   "
    display2:
      text: "BY"
    display3:
      text: "OUTPOST"
    display4:
      text: "KODELIA"
    display5:
      text: "__**_**"
#    dimDisplay4:
  attract_show_4_complete:
    display1:
      text: "This"
    display2:
      text: "Is"
    display3:
      text: "The"
    display4:
      text: "End"
    display5:
      text: "__**_**"


show_player:
  mode_attract_started:
    gi:
      key: gi_show
      priority: 1
      show_tokens:
        tag1: gi
        color1: white
        tag2: pop_cores
        color2: ff7500
    characters_show:
      key: characters_show
      priority: 1
    multipliers_show:
      key: multipliers_show
      priority: 1
    super_bonus_show:
      key: super_bonus_show
      priority: 1
    bonus_show:
      key: bonus_show
      priority: 1
    spinner_show:
      key: spinner_show
      priority: 1
    escape_show:
      key: escape_show
      priority: 1
    drops_show:
      key: drops_show
      priority: 1
    oil_slick_show:
      key: oil_slick_show
      priority: 1
    creek_show:
      key: creek_show
      priority: 1
    hazzard_show:
      key: hazzard_show
      priority: 1
    hazzard_special_show:
      key: hazzard_special_show
      priority: 1
    coin_lights_show:
      key: coin_lights_show_key
      priority: 1
    backbox_test:
      key: backbox_test_key
      loops: -1
      priority: 1
  start_loop:
    red_siren_show:
      action: play
      speed: 60
      loops: 6
      priority: 10
    blue_siren_show:
      action: play
      speed: 60
      loops: 6
      priority: 10
    attract_show_1:
      action: play
      loops: 0
      events_when_completed: attract_show_1_complete
  attract_show_1_complete:
    attract_show_2:
      action: play
      loops: 0
      events_when_completed: attract_show_2_complete
  attract_show_2_complete:
    attract_show_3:
      action: play
      loops: 0
      events_when_completed: attract_show_3_complete
  attract_show_3_complete:
    attract_show_4:
      action: play
      loops: 0
      events_when_completed: attract_show_4_complete, start_loop
#  attract_show_last_game_scores:
#    attract_last_game_scores:
#      action: play
#      priority: 15
#      loops: 6
#      show_tokens:
#        atr_score1: "test1"
#        atr_score2: "test1"
#        atr_score3: "test1"
#        atr_score4: "test1"

shows:
  attract_show_1:
    - duration: 5
  attract_show_2:
    - duration: 5
  attract_show_3:
    - duration: 5
  attract_show_4:
    - duration: 5

#variable_player:
#  mode_attract_started|5000ms:
#    machine.display1: "test"


#show_player:
#   mode_attract_started:
#      display_segment_displays:
#        priority: 10
#
#widget_player:
#   mode_attract_started: backglass
#
#shows:
#   display_segment_displays:
#     - time: 0
#       slides:
#          segment_displaysx:
#            widgets:
#              - type: text
#                text: "DukesOf"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 420
#                y: 624
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "Hazzard"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 624
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "Outpost"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 420
#                y: 224
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "Kodelia"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 224
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "__00_00"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 424
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2

