#config_version=5

mode:
  start_events: boars_nest_big_collect
  stop_events: boars_nest_big_collect_complete
  events_when_started: boars_nest_big_collect_start
  priority: 1500

event_player:
  boars_nest_big_collect_start:
    show_score_flash_text:
      text_1: "All Got"
      text_2: "to the "
      text_3: "BOARS  "
      text_4: "  NEST!"
      events_when_completed: bnbc_1
  bnbc_1:
    show_score_flash_text:
      text_1: "INSERT "
      text_2: "JACKPOT"
      text_3: "SHOW   "
      text_4: "   HERE"
      events_when_completed: bnbc_2
  bnbc_2:
    show_score_flash_text:
      text_1: "OneMore"
      text_2: "Set Of "
      text_3: "DISPLAY"
      text_4: "For Fun"
      events_when_completed: bnbc_3
  bnbc_3:
    - boars_nest_ended
    - boars_nest_ended_complete
    - boars_nest_ended_reset_vars
    - boars_nest_audio_reset
    - boars_nest_end_collect
  boars_nest_end_collect:
    - drops_inline_reset
    - boars_nest_escape_saucer_eject
  boars_nest_escape_saucer_eject{device.playfields.playfield.balls>1}:
    - boars_nest_escape_saucer_eject|500ms
  boars_nest_escape_saucer_eject{device.playfields.playfield.balls==1}:
    - enable_playfield_coils
    - escape_saucer_eject
    - next_song
    - boars_nest_big_collect_complete|100ms

variable_player:
  boars_nest_ended_reset_vars:
    boars_nest_active:
      action: set
      int: 0
    boars_nest_six_pack_complete:
      action: set
      int: 0
    boars_nest_spins:
      action: set
      int: 0
    boars_nest_pops:
      action: set
      int: 0
    boars_nest_right_drops:
      action: set
      int: 0
    boars_nest_oil_slicks:
      action: set
      int: 0
    boars_nest_creeks:
      action: set
      int: 0
    boars_nest_hazzards:
      action: set
      int: 0
    boars_nest_inlines:
      action: set
      int: 0
  boars_nest_big_collect_start:
    boars_nest_jackpot:
      action: set
      int: 100000
sound_player:
  boars_nest_audio_reset:
    doh_theme:
      action: stop
      fade_out: 500ms
