#config_version=5

mode:
  start_events: boars_nest_big_collect
  stop_events: boars_nest_big_collect_complete
  events_when_started: boars_nest_big_collect_start
  priority: 1500

event_player:
  boars_nest_big_collect_start:
    show_score_flash_text:
      text_1: "All Got"
      text_2: "to the "
      text_3: "BOARS  "
      text_4: "  NEST!"
      events_when_completed: bnbc_1
  bnbc_1:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "BO     "
      score_value:
        value: current_player.boars_nest_spins * 800
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot + (current_player.boars_nest_spins * 800)
        type: int
      events_when_completed: bnbc_1_set
  bnbc_1_set:
    - bnbc_2
  bnbc_2:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "LUKE   "
      score_value:
        value: current_player.boars_nest_pops * 800
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot + (current_player.boars_nest_pops * 800)
        type: int
      events_when_completed: bnbc_2_set
  bnbc_2_set:
    - bnbc_3
  bnbc_3:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "DAISY  "
      score_value:
        value: current_player.boars_nest_right_drops * 3000
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot + (current_player.boars_nest_right_drops * 3000)
        type: int
      events_when_completed: bnbc_3_set
  bnbc_3_set:
    - bnbc_4
  bnbc_4:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "JESSE  "
      score_value:
        value: current_player.boars_nest_oil_slicks * 8000
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot + (current_player.boars_nest_oil_slicks * 8000)
        type: int
      events_when_completed: bnbc_4_set
  bnbc_4_set:
    - bnbc_5
  bnbc_5:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "COOTER "
      score_value:
        value: current_player.boars_nest_creeks * 4000
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot + (current_player.boars_nest_creeks * 4000)
        type: int
      events_when_completed: bnbc_5_set
  bnbc_5_set:
    - bnbc_6
  bnbc_6:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "ROSCO  "
      score_value:
        value: current_player.boars_nest_hazzards * 4000
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot + (current_player.boars_nest_hazzards * 4000)
        type: int
      events_when_completed: bnbc_6_set
  bnbc_6_set:
    - bnbc_7
  bnbc_7{current_player.total_super_jackpots_scored>0}:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "SUPERS "
      score_value:
        value: current_player.total_super_jackpots_scored
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot + (current_player.total_super_jackpots_scored)
        type: int
      events_when_completed: bnbc_7_set
    boars_nest_super_show:
      value: dummy
  bnbc_7_set:
    - bnbc_8
  bnbc_7{current_player.total_super_jackpots_scored==0}:
    - bnbc_8
  bnbc_8{current_player.boars_nest_inlines > 3}:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "HOGG   "
      score_value: "DOUBLED"
      boar_score_post:
        value: current_player.boars_nest_jackpot + current_player.boars_nest_jackpot
        type: int
      events_when_completed: bnbc_2x
  bnbc_8{current_player.boars_nest_inlines <= 3}:
    - bnbc_9
  bnbc_2x:
    - bnbc_9
  bnbc_9:
    boars_nest_show_bonus_text:
      boar_score_pre:
        value: current_player.boars_nest_jackpot
        type: int
      score_type: "FINAL  "
      score_value:
        value: current_player.boars_nest_jackpot
        type: int
      boar_score_post:
        value: current_player.boars_nest_jackpot
        type: int
      events_when_completed: bnbc_collect
  bnbc_collect:
    - bnbc_ended
  bnbc_ended:
    - boars_nest_ended
    - boars_nest_ended_complete
    - boars_nest_ended_reset_vars
    - boars_nest_audio_reset
    - boars_nest_end_collect
  boars_nest_end_collect:
    - drops_inline_reset
    - boars_nest_escape_saucer_eject
  boars_nest_escape_saucer_eject{device.playfields.playfield.balls>1}:
    - boars_nest_escape_saucer_eject|500ms
  boars_nest_escape_saucer_eject{device.playfields.playfield.balls==1}:
    - enable_playfield_coils
    - escape_saucer_eject
    - next_song
    - boars_nest_big_collect_complete|100ms

variable_player:
  boars_nest_ended_reset_vars:
    boars_nest_active:
      action: set
      int: 0
    boars_nest_six_pack_complete:
      action: set
      int: 0
    boars_nest_spins:
      action: set
      int: 0
    boars_nest_pops:
      action: set
      int: 0
    boars_nest_right_drops:
      action: set
      int: 0
    boars_nest_oil_slicks:
      action: set
      int: 0
    boars_nest_creeks:
      action: set
      int: 0
    boars_nest_hazzards:
      action: set
      int: 0
    boars_nest_inlines:
      action: set
      int: 0
    total_super_jackpots_scored:
      action: set
      int: 0
  boars_nest_big_collect_start:
    boars_nest_jackpot:
      action: set
      int: 100000
  bnbc_1_set:
    boars_nest_jackpot:
      action: add
      int: current_player.boars_nest_spins * 1000
  bnbc_2_set:
    boars_nest_jackpot:
      action: add
      int: current_player.boars_nest_pops * 1000
  bnbc_3_set:
    boars_nest_jackpot:
      action: add
      int: current_player.boars_nest_right_drops * 1000
  bnbc_4_set:
    boars_nest_jackpot:
      action: add
      int: current_player.boars_nest_oil_slicks * 1000
  bnbc_5_set:
    boars_nest_jackpot:
      action: add
      int: current_player.boars_nest_creeks * 1000
  bnbc_6_set:
    boars_nest_jackpot:
      action: add
      int: current_player.boars_nest_hazzards * 1000
  bnbc_7_set:
    boars_nest_jackpot:
      action: add
      int: current_player.total_super_jackpots_scored
  bnbc_2x:
    boars_nest_jackpot:
      action: add
      int: current_player.boars_nest_jackpot
  bnbc_collect:
    score:
      action: add
      int: current_player.boars_nest_jackpot

sound_player:
  boars_nest_big_collect_start:
    doh_theme:
      action: stop
      fade_out: 500ms
    boss_hurry_up:
      action: play
    end_theme:
      action: play
  boars_nest_audio_reset:
    end_theme:
      action: stop
      fade_out: 500ms
  bnbc_1:
    bo_yehaw:
      action: play
  bnbc_2:
    luke_showed_him:
      action: play
  bnbc_3:
    daisy_my_car:
      action: play
  bnbc_4:
    jessie_one_of_the_best:
      action: play
  bnbc_5:
    cooter_take_it_easy:
      action: play
  bnbc_6:
    sheriff_never_seen:
      action: play
  bnbc_8:
    boss_counting_money:
      action: play

show_player:
  boars_nest_big_collect_start:
    gi_dim_show:
      action: play
      priority: 55000
    suppress_collect_lights_show:
      action: play
      priority: 55000
  bnbc_1:
    bnbc_1_show:
      key: bnbc_1_show_key
      action: play
      loops: 0
      priority: 60000
    bnbc_1_face_show:
      key: bnbc_1_face_show_key
      action: play
      loops: -1
      priority: 60000
  bnbc_2:
    bnbc_1_show_key: stop
    bnbc_1_face_show_key: stop
    bnbc_2_show:
      key: bnbc_2_show_key
      action: play
      loops: 0
      priority: 60000
    bnbc_2_face_show:
      key: bnbc_2_face_show_key
      action: play
      loops: -1
      priority: 60000
  bnbc_3:
    bnbc_2_show_key: stop
    bnbc_2_face_show_key: stop
    bnbc_3_show:
      key: bnbc_3_show_key
      action: play
      loops: 0
      priority: 60000
    bnbc_3_face_show:
      key: bnbc_3_face_show_key
      action: play
      loops: -1
      priority: 60000
  bnbc_4:
    bnbc_3_show_key: stop
    bnbc_3_face_show_key: stop
    bnbc_4_show:
      key: bnbc_4_show_key
      action: play
      loops: 0
      priority: 60000
    bnbc_4_face_show:
      key: bnbc_4_face_show_key
      action: play
      loops: -1
      priority: 60000
  bnbc_5:
    bnbc_4_show_key: stop
    bnbc_4_face_show_key: stop
    bnbc_5_show:
      key: bnbc_5_show_key
      action: play
      loops: 0
      priority: 60000
    bnbc_5_face_show:
      key: bnbc_5_face_show_key
      action: play
      loops: -1
      priority: 60000
  bnbc_6:
    bnbc_5_show_key: stop
    bnbc_5_face_show_key: stop
    bnbc_6_show:
      key: bnbc_6_show_key
      action: play
      loops: 0
      priority: 60000
    bnbc_6_face_show:
      key: bnbc_6_face_show_key
      action: play
      loops: -1
      priority: 60000
  bnbc_7:
    bnbc_6_show_key: stop
    bnbc_6_face_show_key: stop
  bnbc_8:
    bnbc_8_show:
      key: bnbc_8_show_key
      action: play
      loops: 0
      priority: 60000
    bnbc_8_face_show:
      key: bnbc_8_face_show_key
      action: play
      loops: -1
      priority: 60000
  bnbc_9:
    bnbc_8_show_key: stop
    bnbc_8_face_show_key: stop
    bnbc_9_show:
      key: bnbc_9_show_key
      action: play
      speed: 40
      loops: 4
      priority: 60000