#config_version=5

mode:
  start_events: ball_starting
  priority: 100
  file_log: full



variable_player:
  # PARAGON base wiring treats top right, drop target rebounds and golden cliffs rollover as switch #34 (10 point rebound)
  s_top_center_rollover_active:
    score: 10
  s_drop_inline_a_active:
    score: 100

ball_saves:
  ball_save_main:
    active_time: 10s
    hurry_up_time: 3s
    timer_start_events: playfield_active
    auto_launch: true
    balls_to_save: 1

show_player:
  ball_save_ball_save_main_timer_start:
    ball_save_flash:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_bonus_shoot_again, l_bonus_shoot_again2
        color: orange
  ball_save_ball_save_main_hurry_up:
    ball_save_flash:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_bonus_shoot_again, l_bonus_shoot_again2
        color: orange
  ball_save_ball_save_main_disabled:
    ball_save: stop
