#config_version=5

mode:
  start_events: ball_starting
  priority: 100
  file_log: full



variable_player:
  # PARAGON base wiring treats top right, drop target rebounds and golden cliffs rollover as switch #34 (10 point rebound)
  s_top_center_rollover_active:
    score: 10
  s_drop_inline_a_active:
    score: 100

#The first ball save is the "playfield validation" save and will save unlimited balls until
#a switch with the "kpf" tag is registered.  Once this happens, the real ball save starts
#which is time limited and will save at most one ball.

ball_saves:
  ball_save_validate:
    balls_to_save: -1
    disable_events: sw_kpf
    auto_launch: false
    early_ball_save_events: sw_early_ball_save

  ball_save_main:
    active_time: settings.initial_ball_save
    hurry_up_time: 4s
    grace_period: 3s
    enable_events: ball_save_ball_save_validate_disabled{settings.initial_ball_save>0}
    auto_launch: true
    balls_to_save: 1
    early_ball_save_events: sw_early_ball_save

show_player:
  ball_save_ball_save_main_timer_start:
    ball_save_flash:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_bonus_shoot_again, l_bonus_shoot_again2, l_bonus_shoot_again3
        color: ff7500
  ball_save_ball_save_main_hurry_up:
    ball_save_flash:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_bonus_shoot_again, l_bonus_shoot_again2, l_bonus_shoot_again3
        color: ff7500
  ball_save_ball_save_main_disabled:
    ball_save: stop
