#config_version=5

mode:
  start_events: ball_search_phase_1
  stop_events: end_inline_ball_search
  events_when_started: trigger_knockdown_coils
  priority: 1000

event_player:
  trigger_knockdown_coils:
    - escape_saucer_eject
    - do_the_drops_now
  do_the_drops_now:
    - knockdown_drop_a
    - knockdown_drop_b
    - knockdown_drop_c
    - knockdown_drop_d
    - kd_reset|1000ms
  kd_reset:
    - drops_inline_reset
    - kd_trigger_knockdown_coils|250ms
    - end_inline_ball_search|750ms
  kd_trigger_knockdown_coils{settings.inline_memory_feature==1 and current_player.in_line_a_down>0}:
    - knockdown_drop_a
  kd_trigger_knockdown_coils{settings.inline_memory_feature==1 and current_player.in_line_b_down>0}:
    - knockdown_drop_b
  kd_trigger_knockdown_coils{settings.inline_memory_feature==1 and current_player.in_line_c_down>0}:
    - knockdown_drop_c
  kd_trigger_knockdown_coils{settings.inline_memory_feature==1 and current_player.in_line_d_down>0}:
    - knockdown_drop_d

variable_player:
  shot_group_drop_inline_hit{settings.in_line_scoring==0}:
    score:
      int: 0
      action: add
      block: true
    bonuscount:
      int: 0
      action: add
      block: true
  shot_group_drop_inline_hit{settings.in_line_scoring==1}:
    score:
      int: 0
      action: add
      block: true
    bonuscount:
      int: 0
      action: add
      block: true
  trigger_knockdown_coils:
    suspend_spot: 1
  ball_search_stopped:
    suspend_spot:
      action: set
      int: 0
  ball_search_failed:
    suspend_spot:
      action: set
      int: 0
