#config_version=6

# Contains configuration data for the right 3-bank of drop targets
# Bank - "dtbank_right"

# Based on PARAGON Rules --
# Drop targets award 500 points
# Completion of bank awards 10k, 15k, 20k, 25k, SPECIAL
# SETTING determines if bank reverts to 25k after scoring SPECIAL or stays on SPECIAL


mode:
  start_events: ball_started
  events_when_started: init_right_drops
  priority: 110

counters:
  counter_drop_right_complete:
    count_events: drop_target_bank_dtbank_right_down
    control_events:
      - event: drop_right_set_count_3
        action: subtract
        value: 2
      - event: drop_right_set_count_4
        action: subtract
        value: 1
    reset_on_complete: False
    count_complete_value: 6
    persist_state: true
    disable_events: boars_nest_started
    enable_events: init_right_drops, boars_nest_ended_complete, boars_nest_ended_failed

show_player:
  logicblock_counter_drop_right_complete_updated{value==0}:
    right_drop_10k:
      key: right_drop_show
  logicblock_counter_drop_right_complete_updated{value==1}:
    right_drop_15k:
      key: right_drop_show
  logicblock_counter_drop_right_complete_updated{value==2}:
    right_drop_20k:
      key: right_drop_show
  logicblock_counter_drop_right_complete_updated{value==3}:
    right_drop_25k:
      key: right_drop_show
  drop_right_set_count_3:
    right_drop_25k:
      key: right_drop_show
  logicblock_counter_drop_right_complete_updated{value==4}:
    right_bank_special:
      key: right_drop_show
  drop_right_set_count_4:
    right_bank_special:
      key: right_drop_show

shots:
  shot_drop_right_a:
    switch: s_drop_right_a
  shot_drop_right_b:
    switch: s_drop_right_b
  shot_drop_right_c:
    switch: s_drop_right_c

shot_groups:
   shot_group_drop_right:
     shots: shot_drop_right_a, shot_drop_right_b, shot_drop_right_c
     reset_events: zzz_placeholder_drop_right_reset
     enable_events: init_right_drops
     disable_events: ball_ending

event_player:
   logicblock_counter_drop_right_complete_hit{count==5}:
     - special_scored_drop_right
     - drop_right_special_check
# Revert to 25k after SPECIAL
   drop_right_special_check{settings.waterfall_drops_special==0}:
     - drop_right_set_count_3
# Stay on SPECIAL after SPECIAL
   drop_right_special_check{settings.waterfall_drops_special==1}:
     - drop_right_set_count_4

variable_player:
   shot_group_drop_right_hit:
     score: 500
   logicblock_counter_drop_right_complete_hit{count==1}:
     score: 10000
   logicblock_counter_drop_right_complete_hit{count==2}:
     score: 15000
   logicblock_counter_drop_right_complete_hit{count==3}:
     score: 20000
   logicblock_counter_drop_right_complete_hit{count==4}:
     score: 25000
