#config_version=5

# River Multi-ball is Ready

# EVENTS --
# multiball_hazzard_multiball_started
# multiball_hazzard_multiball_shoot_again
# multiball_hazzard_multiball_lost_ball
# multiball_hazzard_multiball_shoot_again_ended
# multiball_hazzard_multiball_ended

#TODO Show on multiball ready to start
#TODO Start Event: enable_hazzard_multiball_start
#TODO End Event:   start_hazzard_multiball
#
#TODO Show on Hazzard Jackpot Ready
#TODO Start Event: start_hazzard_multiball, hazzard_super_jackpot_collected
#TODO End Event  : hazzard_super_jackpot_enabled
#
#TODO Show on Hazzard Super Jackpot Ready, Draw attention to jackpot doubler (spinner)
#TODO Start Event: hazzard_super_jackpot_enabled
#TODO End Event  : hazzard_super_jackpot_collected
#
#TODO Show on Jackpot Collect
#TODO Play Event: hazzard_jackpot_collected
#
#TODO Show on Super Jackpot Doubled
#TODO Play Event: player_hazzard_spinner_count{current_player.hazzard_spinner_count>=20 and current_player.hazzard_jackpot_multiplier==1 and current_player.hazzard_jackpot_count>=3}
#TODO Stop Show -- whatever draws attention to the spinner
#
#TODO Show on Super Jackpot Collect
#TODO Play Event: hazzard_super_jackpot_collected

mode:
  start_events: start_mode_hazzard_multiball
  stop_events: hazzard_mball_mode_stop, tilt
  events_when_started: disable_base_hazzard_shot, enable_hazzard_multiball_start
  events_when_stopped: enable_base_creek_shot
  priority: 200

state_machines:
  hazzard_notify_state:
    states:
      start:
        label: start_state
      step1:
        label: end_state
    transitions:
      - source: start
        target: step1
        events: show_hazzard_mball_done

event_player:
  show_hazzard_multiball_notify{device.state_machines.hazzard_notify_state.state == "start"}:
    show_notify_flash_text:
      text_1: "HAZZARD"
      text_2: "M-BALL"
      text_3: "READY "
      text_4: "*******"
      events_when_completed: show_hazzard_mball_done
  hazzard_multiball_start_hit:
    - start_hazzard_multiball
  sw_h_jack{current_player.hazzard_jackpot_count<3}:
    - increment_hazzard_jackpot
  hazzard_collect_jackpot_hit:
    - hazzard_jackpot_collected
  player_hazzard_jackpot_count{current_player.hazzard_jackpot_count>=3}:
    - hazzard_super_jackpot_enabled
    - multiball_display_hazzard
  hazzard_enhance_jackpot_hit:
    - hazzard_super_jackpot_enhanced
  hazzard_collect_super_jackpot_hit:
    - hazzard_super_jackpot_collected
    - multiball_display_hazzard
  multiball_hazzard_multiball_started:
    - hazzard_ach_reset
  multiball_hazzard_multiball_ended:
    - hazzard_ach_init
    - hazzard_mball_mode_stop

shots:
  hazzard_multiball_start:
    switch: s_saucer_paragon
    disable_events: multiball_hazzard_multiball_started, disable_two_ball_multiball_progress
    enable_events: enable_hazzard_multiball_start, boars_nest_ended, end_chase_mode
  hazzard_collect_jackpot:
    switch: s_saucer_paragon
    disable_events: hazzard_super_jackpot_enabled
    enable_events: multiball_hazzard_multiball_started, hazzard_super_jackpot_collected
  hazzard_enhance_jackpot:
    switch: s_saucer_paragon
    disable_events: hazzard_super_jackpot_collected
    enable_events: hazzard_super_jackpot_enabled
  hazzard_collect_super_jackpot:
    switch: s_waterfall_rollover
    enable_events: hazzard_super_jackpot_enabled
    disable_events: hazzard_super_jackpot_collected

multiballs:
  hazzard_multiball:
    ball_count: 1
    ball_count_type: add
    # seems to default to MS here, whereas it does not do so if done as a ball save
    shoot_again: settings.hazzard_ball_save * 1000
    start_events: start_hazzard_multiball

show_player:
  multiball_hazzard_multiball_started:
    ball_save_flash:
      key: ball_save_hazzard
      speed: 2
      show_tokens:
        lights: l_bonus_shoot_again, l_bonus_shoot_again2, l_bonus_shoot_again3
        color: orange
  multiball_hazzard_multiball_shoot_again_ended:
    ball_save_hazzard: stop
  enable_hazzard_multiball_start:
    hazzard_saucer_focus_show:
      key: hazzard_saucer_focus_show_key
      speed: 1
      priority: 1000
      loops: 0
      events_when_completed: hazzard_saucer_post_focus_show
  hazzard_saucer_post_focus_show:
    hazzard_saucer_post_focus_show:
      key: hazzard_saucer_post_focus_show_key
      speed: 1
      priority: 1000

# Kill the multiball show if you can no longer start it
  disable_two_ball_multiball_progress:
    hazzard_saucer_post_focus_show_key: stop

  start_hazzard_multiball:
    hazzard_saucer_post_focus_show_key: stop
    hazzard_saucer_jackpot_ready_show:
      key: hazzard_saucer_jackpot_ready_show_key
      speed: 1
      priority: 1000
    jackpot_show:
      speed: 1
      loops: 5
      priority: 2000
      show_tokens:
        color: FF7500
        color2: FF7500
  hazzard_super_jackpot_collected:
    hazzard_saucer_jackpot_ready_show:
      key: hazzard_saucer_jackpot_ready_show_key
      speed: 1
      priority: 1000
  hazzard_super_jackpot_enabled:
    hazzard_saucer_jackpot_ready_show_key: stop
    hazzard_super_jackpot_focus_show:
      key: hazzard_super_jackpot_focus_show_key
      speed: 1
      priority: 1500
      loops: 0
      events_when_completed: hazzard_super_jackpot_post_focus
  multiball_hazzard_multiball_ended:
    hazzard_saucer_jackpot_ready_show_key: stop
  player_hazzard_jackpot_count{current_player.hazzard_jackpot_count<3 and current_player.hazzard_jackpot_count>0}:
    jackpot_show:
      speed: 1
      loops: 2
      priority: 2000
      show_tokens:
        color: FF7500
        color2: FF7500

variable_player:
  multiball_hazzard_multiball_started:
    hazzard_jackpot:
      action: set
      int: 10000
    hazzard_superjackpot:
      action: set
      int: 0
    hazzard_jackpot_increment_value:
      action: set
      int: 0
    hazzard_jackpot_count:
      action: set
      int: 0
    hazzard_jackpot_multiplier:
      action: set
      int: 1
    hazzard_spinner_count:
      action: set
      int: 0
  increment_hazzard_jackpot:
    hazzard_jackpot_increment_value:
      int: 100
    hazzard_jackpot:
      int: current_player.hazzard_jackpot_increment_value - 100
  hazzard_jackpot_collected:
    hazzard_jackpot_count:
      int: 1
    score:
      int: current_player.hazzard_jackpot
    hazzard_superjackpot:
      int: current_player.hazzard_jackpot
    hazzard_last_jackpot_collected:
      action: set
      int: current_player.hazzard_jackpot
    hazzard_jackpot:
      action: set
      int: 9900
    hazzard_jackpot_increment_value:
      action: set
      int: 0
    hazzard_last_super_jackpot_collected:
      action: set
      int: 0
  hazzard_super_jackpot_enabled:
    hazzard_jackpot_multiplier:
      action: set
      int: 1
    hazzard_spinner_count:
      action: set
      int: 0
  spinner_default_hit:
    hazzard_spinner_count:
      int: 1
  player_hazzard_spinner_count{current_player.hazzard_spinner_count>=20 and current_player.hazzard_jackpot_multiplier==1 and current_player.hazzard_jackpot_count>=3}:
    hazzard_jackpot_multiplier:
      action: set
      int: 2
  hazzard_super_jackpot_enhanced:
    hazzard_superjackpot:
      int: 10000
  hazzard_super_jackpot_collected:
    score:
      int: current_player.hazzard_superjackpot * current_player.hazzard_jackpot_multiplier
    total_super_jackpots_scored:
      int: current_player.hazzard_superjackpot * current_player.hazzard_jackpot_multiplier
    hazzard_last_super_jackpot_collected:
      action: set
      int: current_player.hazzard_superjackpot * current_player.hazzard_jackpot_multiplier
    hazzard_jackpot:
      action: set
      int: 10000
    hazzard_superjackpot:
      action: set
      int: 0
    hazzard_jackpot_increment_value:
      action: set
      int: 0
    hazzard_jackpot_count:
      action: set
      int: 0

# it would seem that a single segment display player within a mode cannot "stack"
# they need to be in different modes for this to work?  Below does not return
# when in the multiball_display.yaml mode file.
segment_display_player:
  multiball_display_creek{device.multiballs.creek_multiball.balls_live_target>0}:
    display1:
      action: remove
      key: hazzard_1
    display2:
      action: remove
      key: hazzard_2
    display3:
      action: remove
      key: hazzard_3
    display4:
      action: remove
      key: hazzard_4
  multiball_display_chase{device.multiballs.pre_chase_multiball.balls_live_target>0}:
    display1:
      action: remove
      key: hazzard_1
    display2:
      action: remove
      key: hazzard_2
    display3:
      action: remove
      key: hazzard_3
    display4:
      action: remove
      key: hazzard_4
  multiball_display_boar{current_player.boars_nest_active>0}:
    display1:
      action: remove
      key: hazzard_1
    display2:
      action: remove
      key: hazzard_2
    display3:
      action: remove
      key: hazzard_3
    display4:
      action: remove
      key: hazzard_4

  multiball_display_hazzard{device.multiballs.hazzard_multiball.balls_live_target>0 and current_player.hazzard_jackpot_count<3}:
    display1:
      action: add
      key: hazzard_1
      priority: 400
      text: "Player{current_player.number}"
    display2:
      action: add
      key: hazzard_2
      priority: 400
      text: "{current_player.score:d}"
    display3:
      action: add
      key: hazzard_3
      priority: 400
      text: "Hz JACK"
    display4:
      action: add
      key: hazzard_4
      priority: 400
      text: "{current_player.hazzard_jackpot:d}"
  multiball_display_hazzard{current_player.hazzard_jackpot_count>=3}:
    display1:
      action: add
      key: hazzard_1
      priority: 400
      text: "Player{current_player.number}"
    display2:
      action: add
      key: hazzard_2
      priority: 400
      text: "{current_player.score:d}"
    display3:
      action: add
      key: hazzard_3
      priority: 400
      text: "HzSUPER"
    display4:
      action: add
      key: hazzard_4
      priority: 400
      text: "{current_player.hazzard_superjackpot:d}"

sound_player:
  enable_hazzard_multiball_start:
    air_force:
      action: play
      loops: 0
  start_hazzard_multiball:
    air_force:
      action: stop
    derby_time:
      action: play
      loops: 0
  hazzard_jackpot_collected:
    derby_time:
      action: stop
    jackpot_clips:
      action: play
      loops: 0