#config_version=5

# River Multi-ball is Ready

# EVENTS --
# multiball_hazzard_multiball_started
# multiball_hazzard_multiball_shoot_again
# multiball_hazzard_multiball_lost_ball
# multiball_hazzard_multiball_shoot_again_ended
# multiball_hazzard_multiball_ended

mode:
  start_events: start_mode_hazzard_multiball
  stop_events: multiball_river_hazzard_ended
  priority: 200

state_machines:
  hazzard_notify_state:
    states:
      start:
        label: start_state
      step1:
        label: end_state
    transitions:
      - source: start
        target: step1
        events: show_hazzard_mball_done

event_player:
  show_hazzard_multiball_notify{device.state_machines.hazzard_notify_state.state == "start"}:
    show_notify_flash_text:
      text_1: "HAZZARD  "
      text_2: "M-BALL"
      text_3: "READY "
      text_4: "*******"
      events_when_completed: show_hazzard_mball_done

multiballs:
  hazzard_multiball:
    ball_count: 1
    ball_count_type: add
    shoot_again: 15s
    start_events: launch_hazzard_multiball

show_player:
  multiball_hazzard_multiball_started:
    ball_save_flash:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_bonus_shoot_again, l_bonus_shoot_again2
        color: orange
  multiball_hazzard_multiball_shoot_again_ended:
    ball_save: stop