#config_version=5

# Contains configuration data for the golden cliffs saucer

# Based on PARAGON Rules --
#
# Each hit of the golden cliffs saucer scores current value and advances to next value, does not reset per ball
#
#TODO -- play a show when hit, then eject the ball

mode:
  start_events: ball_started
  priority: 121

shot_profiles:
  golden_cliffs:
    advance_on_hit: true
    states:
      - name: 2k
        show: gc2k
      - name: 4k
        show: gc4k
      - name: 6k
        show: gc6k
      - name: 8k
        show: gc8k
      - name: 10k
        show: gc10k
      - name: 20k
        show: gc20k

shots:
  golden_cliffs_saucer:
    switch: s_saucer_golden_cliffs
    profile: golden_cliffs

variable_player:
   golden_cliffs_saucer_2k_hit:
     last_creek_value:
       int: 2000
       action: set
   golden_cliffs_saucer_4k_hit:
     last_creek_value:
       int: 4000
       action: set
   golden_cliffs_saucer_6k_hit:
     last_creek_value:
       int: 6000
       action: set
   golden_cliffs_saucer_8k_hit:
     last_creek_value:
       int: 8000
       action: set
   golden_cliffs_saucer_10k_hit:
     last_creek_value:
       int: 10000
       action: set
   golden_cliffs_saucer_20k_hit:
     last_creek_value:
       int: 20000
       action: set
     bonuscount: 1
   player_last_creek_value:
     score:
       int: (value)

event_player:
  golden_cliffs_saucer_20k_hit{current_player.last_creek_value==20000}:
    player_last_creek_value:
      value: 20000

show_player:
  player_last_creek_value:
    score_flash_text:
      loops: 4
      show_tokens:
        text_1: "CREEK  "
        text_2: "VALUE"
        text_3: "SCORES "
        text_4: "{current_player.last_creek_value}"








