#config_version=5

mode:
  start_events: ball_started
  events_when_started: escape_saucer_mode_start
  priority: 1000

shots:
  escape_saucer:
    switch: s_saucer_treasure_chamber

event_player:
  escape_saucer_hit{current_player.boars_nest_six_pack_complete==1}:
    - escape_saucer_boars_nest_collect
  escape_saucer_hit{current_player.boars_nest_six_pack_complete!=1}:
    - escape_saucer_check_chase_start
  escape_saucer_check_chase_start{current_player.boars_nest_active!=1 and settings.chase_multiball_feature==1 and mode.chase_multiball.active==True}:
    - start_chase_sequence
  escape_saucer_check_chase_start{mode.chase_multiball.active==False}:
    - escape_saucer_unexpected
  escape_saucer_unexpected:
    - escape_saucer_eject