#config_version=5

# Contains configuration data for the in line drop targets
# Bank - "dtbank_inline"

# Based on PARAGON Rules --
#TODO fully implement rules here (just initial drops to 5x saucer implemented)

mode:
  start_events: ball_started
  events_when_started: init_inline_drops
  priority: 118

shot_profiles:
  treasure_profile:
    advance_on_hit: true
    states:
      - name: 5x
        show: saucer5x
      - name: special
        show: saucerspecial

shots:
  shot_drop_inline_a:
    switch: s_drop_inline_a
  shot_drop_inline_b:
    switch: s_drop_inline_b
  shot_drop_inline_c:
    switch: s_drop_inline_c
  shot_drop_inline_d:
    switch: s_drop_inline_d
  treasure_saucer:
    switch: s_saucer_treasure_chamber
    profile: treasure_profile
    disable_events: mode_chase_multiball_started
    enable_events: init_inline_drops, mode_chase_multiball_ended, end_chase_mode
    reset_events: drops_shot_profile_reset

shot_groups:
   shot_group_drop_inline:
     shots: shot_drop_inline_a, shot_drop_inline_b, shot_drop_inline_c, shot_drop_inline_d
     reset_events: zzz_placeholder_drop_inline_reset, end_chase_mode
     enable_events: init_inline_drops
     disable_events: ball_ending

event_player:
  shot_drop_inline_c_hit:
    - bonus_multiply_2x
  shot_drop_inline_d_hit:
    - bonus_multiply_3x
  treasure_saucer_5x_hit:
    - bonus_multiply_5x
  shot_group_drop_inline_hit{settings.in_line_spotting==1 and current_player.suspend_spot==0}:
    - spot_hazzard_letter
  shot_drop_inline_d_hit{settings.chase_multiball_feature==1 and current_player.boars_nest_active==0}:
    - start_mode_chase_multiball
#  init_inline_drops{settings.chase_multiball_feature==1 and current_player.in_line_d_down>0}:
#    - start_mode_chase_multiball
  end_chase_mode:
    - drops_inline_reset
    - drops_shot_profile_reset

variable_player:
  shot_group_drop_inline_hit{settings.in_line_scoring==0}:
    score: 1000
    bonuscount: 1
  shot_group_drop_inline_hit{settings.in_line_scoring==1}:
    score: 3000
    bonuscount: 2
  shot_drop_inline_a_hit:
    in_line_a_down: 1
  shot_drop_inline_b_hit:
    in_line_b_down: 1
  shot_drop_inline_c_hit:
    in_line_c_down: 1
  shot_drop_inline_d_hit:
    in_line_d_down: 1
