#config_version=5

# PARAGON - Base Solenoid Identification Table
#
# 01 Outhole Kicker
# 02 Knocker
# 03 Treasure Chamber Saucer
# 04 Paragon Saucer
# 05 Golden Cliffs Saucer
# 06 Left Slingshot
# 07 Right Slingshot
# 08 Left Thumper Bumper
# 09 Right Thumper Bumper
# 10 Bottom Thumper Bumper
# 11 Center Thumper Bumper
# 12 Drop Target (In line)
# 13 Drop Target
# 14 Coin Lockout Door
# 15 K1 relay (flipper enable)

coils:
  c_outhole_kicker:
    number: A0-B0-0
    default_pulse_ms: 15
  c_knocker:
    number: A0-B0-1
    default_pulse_ms: 15
  c_saucer_trasure_chamber:
    number: A0-B0-2
    default_pulse_ms: 15
  c_saucer_paragon:
    number: A0-B0-3
    default_pulse_ms: 15
  c_saucer_golden_cliffs:
    number: A0-B0-4
    default_pulse_ms: 15
  c_left_slingshot:
    number: A0-B0-5
    default_pulse_ms: 12
  c_right_slingshot:
    number: A0-B0-6
    default_pulse_ms: 12
  c_left_thumper:
    number: A0-B0-7
    default_pulse_ms: 20
  c_right_thumper:
    number: A0-B1-0
    default_pulse_ms: 20
  c_bottom_thumper:
    number: A0-B1-1
    default_pulse_ms: 20
  c_center_thumper:
    number: A0-B1-2
    default_pulse_ms: 20
  c_drop_target_inline:
    number: A0-B1-3
    default_pulse_ms: 30
  c_drop_target_right:
    number: A0-B1-4
    default_pulse_ms: 30
  c_coin_lockout_door:
    number: A0-B1-5
    default_pulse_ms: 15
  c_k1_relay_flipper_enable:
    number: A0-B1-6
    default_pulse_ms: 15
  c_flipper_right_main:
    number: A1-B0-0
    default_pulse_ms: 7
    debug: true
    allow_enable: true
  c_flipper_left_main:
    number: A1-B0-1
    default_pulse_ms: 7
    debug: true
    allow_enable: true
  c_flipper_right_upper:
    number: A1-B0-2
    default_pulse_ms: 7
    debug: true
    allow_enable: true
  c_flipper_left_upper:
    number: A1-B0-3
    default_pulse_ms: 7
    debug: true
    allow_enable: true
