#config_version=5

# PARAGON - Base Solenoid Identification Table
#
# 01 Outhole Kicker
# 02 Knocker
# 03 Treasure Chamber Saucer
# 04 Paragon Saucer
# 05 Golden Cliffs Saucer
# 06 Left Slingshot
# 07 Right Slingshot
# 08 Left Thumper Bumper
# 09 Right Thumper Bumper
# 10 Bottom Thumper Bumper
# 11 Center Thumper Bumper
# 12 Drop Target (In line)
# 13 Drop Target
# 14 Coin Lockout Door
# 15 K1 relay (flipper enable)

coils:
  c_outhole_kicker:
    number: 0-0-9
    default_pulse_ms: 15
  c_knocker:
    number: 0-0-7
    default_pulse_ms: 18
  c_saucer_trasure_chamber:
    number: 0-0-15
    default_pulse_ms: 20
  c_saucer_paragon:
    number: 1-0-5
    default_pulse_ms: 20
  c_saucer_golden_cliffs:
    number: 1-0-4
    default_pulse_ms: 20
  c_left_slingshot:
    number: 1-0-3
    default_pulse_ms: 15
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
    #pulse_events: temp_sling_left
  c_right_slingshot:
    number: 1-0-1
    default_pulse_ms: 15
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
    #pulse_events: temp_sling_right

  c_left_thumper:
    number: 1-0-7
    default_pulse_ms: 20
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
    #pulse_events: temp_thumper_left
  c_right_thumper:
    number: 1-0-6
    default_pulse_ms: 20
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
    #pulse_events: temp_thumper_right
  c_bottom_thumper:
    number: 1-0-2
    default_pulse_ms: 20
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
    #pulse_events: temp_thumper_bottom
  c_center_thumper:
    number: 1-0-0
    default_pulse_ms: 20
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
    #pulse_events: temp_thumper_center

  c_drop_target_inline:
    number: 0-0-5
    default_pulse_ms: 50
  c_drop_target_right:
    number: 0-0-14
    default_pulse_ms: 45
  c_flipper_right_main:
    number: 0-0-10
    default_pulse_ms: 25
    #debug: true
    #allow_enable: true
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
  c_flipper_left_main:
    number: 0-0-8
    default_pulse_ms: 25
    #debug: true
    #allow_enable: true
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
  c_flipper_right_upper:
    number: 0-0-11
    default_pulse_ms: 25
    #debug: true
    #allow_enable: true
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils
  c_flipper_left_upper:
    number: 0-0-6
    default_pulse_ms: 17
    #debug: true
    #allow_enable: true
    default_hold_power: 0.125
    enable_events: ball_started, enable_playfield_coils
    disable_events: disable_playfield_coils

# Non-Paragon Coils
  c_auto_plunge:
    number: 0-0-12
    default_pulse_ms: 17
    debug: true
    allow_enable: true
  c_ball_trough:
    number: 0-0-0
    default_pulse_ms: 17
    debug: true
    allow_enable: true
  c_inline_knockdown_a:
    number: 0-0-4
    default_pulse_ms: 9
    debug: true
    allow_enable: true
    pulse_events: init_inline_drops{settings.inline_memory_feature==1 and current_player.in_line_a_down>0}, inline_drop_all
  c_inline_knockdown_b:
    number: 0-0-3
    default_pulse_ms: 9
    debug: true
    allow_enable: true
    pulse_events: init_inline_drops{settings.inline_memory_feature==1 and current_player.in_line_b_down>0}, inline_drop_all
  c_inline_knockdown_c:
    number: 0-0-2
    default_pulse_ms: 9
    debug: true
    allow_enable: true
    pulse_events: init_inline_drops{settings.inline_memory_feature==1 and current_player.in_line_c_down>0}, inline_drop_all
  c_inline_knockdown_d:
    number: 0-0-1
    default_pulse_ms: 9
    debug: true
    allow_enable: true
    pulse_events: init_inline_drops{settings.inline_memory_feature==1 and current_player.in_line_d_down>0}, inline_drop_all


autofire_coils:
  slingshot_left:
    coil: c_left_slingshot
    #switch: s_slingshot_left
    switch: s_center_target
    timeout_watch_time: 1s
    timeout_max_hits: 1
    timeout_disable_time: 300ms
  slingshot_right:
    coil: c_right_slingshot
    #switch: s_slingshot_right
    switch: s_rebound_500pt
    timeout_watch_time: 1s
    timeout_max_hits: 1
    timeout_disable_time: 300ms
  thumper_bottom:
    coil: c_bottom_thumper
    #switch: s_thumper_bottom
    switch: s_trough_3
  thumper_center:
    coil: c_center_thumper
    #switch: s_thumper_center
    switch: s_thumper_left
  thumper_right:
    coil: c_right_thumper
    #switch: s_thumper_right
    switch: s_void
  thumper_left:
    coil: c_left_thumper
    #switch: s_thumper_left
    switch: s_thumper_center