#config_version=5
config:
  - hardware.yaml
  - sound.yaml
  - assets.yaml
  - lights.yaml
  - scriptlets.yaml
  - switches.yaml

#slides:
#  welcome_slide:
#    widgets:
#      - type: text
#        text: PINBALL!
#        font_size: 50
#        color: red
#      - type: rectangle
#        width: 240
#        height: 60
#
#slide_player:
#  init_done: welcome_slide

modes:
  - base

player_vars:

## Normal Game Settings

keyboard:
