#config_version=5
config:
  - hardware.yaml
  - switches.yaml
  - coils.yaml
  - display.yaml
  - sound.yaml
  - assets.yaml
  - lights.yaml
  - neoseglights.yaml
  - scriptlets.yaml
  - settings.yaml
  - widgetstyles.yaml
  - widgets.yaml
  - slides.yaml
  - segmentdisplays.yaml
  - game.yaml

custom_code:
  - code.updateMachineVar.updateMachineVar
  - code.scoreFlash.scoreFlash

# This is for the debug only segment display simulation
slide_player:
  init_done: screen_segement_display

widget_player:
  init_done:
    backglass:
      slide: screen_segement_display
    display1:
      slide: screen_segement_display
    display2:
      slide: screen_segement_display
    display3:
      slide: screen_segement_display
    display4:
      slide: screen_segement_display
    display5:
      slide: screen_segement_display

modes:
  - base
  - attract
  - service
  - right_drops       # handler for the right bank drop target feature
  - special           # handler for all SPECIAL events
  - bonus_display     # handler for super bonus and bonus display (maybe countdown?)
  - waterfall         # handler for the waterfall lane feature
  - golden_cliffs     # handler for golden cliffs saucer
  - river_multiball   # handler for the river multiball
  - minor_shots       # misc rollovers / stand ups scoring & bonus accural
  - treasure_chamber  # in line drop targets & associated saucer
  - end_of_ball       # bonus meltdown
  - spinner           # spinner logic
  - thumpers          # thumper bumper logic
  - hazzard           # HAZZARD (Paragon) Saucer
  - hazzard_multiball # HAZZARD multiball feature
  - credits           # credits/freeplay control

credits:
  max_credits: settings.maximum_credits
  free_play: false
  switches:
    - switch: s_coin_1
      type: money
      value: .25
    - switch: s_coin_2
      type: money
      value: .25
    - switch: s_coin_3
      type: money
      value: .25
  pricing_tiers:
    - price: .25
      credits: 1
    - price: 1
      credits: 5
  events:
    - event: award_special_replay
      type: special
      credits: 1

player_vars:
  last_creek_value:
    initial_value: 0
  bonusmulti:
    initial_value: 1
  in_line_a_down:
    initial_value: 0
  in_line_b_down:
    initial_value: 0
  in_line_c_down:
    initial_value: 0
  in_line_d_down:
    initial_value: 0

## Normal Game Settings

keyboard:
  q:
     switch: s_drop_inline_a
  w:
     switch: s_drop_inline_b
  e:
     switch: s_drop_inline_c
  r:
     switch: s_drop_inline_d
  s:
     switch: s_credit_button
  d:
     switch: s_outhole
  t:
     switch: s_tilt
  1:
     switch: s_coin_1
  2:
     switch: s_coin_2
  3:
     switch: s_coin_3
  8:
     switch: s_service_0
  9:
     switch: s_service_1
  0:
     switch: s_service_2
  c:
     switch: s_service_3
  y:
     switch: s_drop_right_a
  u:
     switch: s_drop_right_b
  i:
     switch: s_drop_right_c
  z:
     switch: s_flipper_left
  /:
     switch: s_flipper_right
  x:
     switch: s_slingshot_left
  .:
     switch: s_slingshot_right
  4:
     switch: s_thumper_center
  5:
     switch: s_thumper_right
  6:
     switch: s_thumper_left
  7:
     switch: s_thumper_bottom
  j:
     switch: s_saucer_paragon
  k:
     switch: s_saucer_golden_cliffs
  l:
     switch: s_saucer_treasure_chamber
  f:
     switch: s_top_center_target
  g:
     switch: s_center_target
  h:
     switch: s_rebound_500pt
  ",":
     switch: s_right_flip_feeder_lane
  m:
     switch: s_right_outlane
  p:
     switch: s_spinner
  v:
     switch: s_top_center_rollover
  b:
     switch: s_waterfall_rollover
  n:
     switch: s_golden_cliffs_rollover
