#config_version=5

displays:
  lcd:
    width: 800
    height: 480
    default: true

window:
  width: 800
  height: 480
  title: DoH
  resizable: false
  #TODO when finally done with everything, set fullscreen to true.
  fullscreen: false
  borderless: true
  exit_on_escape: true
  source_display: lcd
