#config_version=5

# PARAGON - Feature Lights
# Note - Light Matrix documentation not present, data is from Lamp Driver Schematic
# Total of 60 controlled lights identified on Schematic
#
# J1 Header - To Playfield
# 18 1K Bonus
# 19 5K Bonus
# 17 9K Bonus
# 23 40K Super Bonus
# 14 25K Drop Target
# 15 2X Bonus
# 16 Saucer "P"
# 28 Saucer "G"
# 24 Center "P"
# 25 Center "G"
# 27 2K Golden Cliff
# 01 2k Bonus
# 09 6k Bonus
# 08 10k Bonus
# 03 10k Drop Target
# 02 Water Lane Special
# 10 3X Bonus
# 07 Saucer "A" (Left)
# 06 Saucer "O"
# 05 Center "A" (Left)
# 11 Center "O"
# 13 Saucer "N"
# 12 4k Golden Cliff
#
# J2 Header - To backbox
# 21 Shoot Again
# 22 Ball in Play
# 16 Spinner (1) Bottom
# 14 10K Waterlane
# 08 Match
# 23 High Score To Date
# 20 Spinner (2)
# 15 5K Waterlane
# 11 Game Over
# 06 Spinner (3)
# 02 10K Golden Cliff
# 10 Tilt
# 07 Spinner (4) Top
# 01 20K Golden Cliff
#
# J3 Header - To Playfield
# 26 3k Bonus
# 25 7k Bonus
# 19 20k Super Bonus
# 17 15k Drop Target
# 16 Paragon Saucer Special
# 23 5x Bonus
# 27 Saucer "R"
# 21 Center "R"
# 20 Center "N"
# 22 Same Player S.A.
# 24 6K Golden Cliff
# 01 4k Bonus
# 12 8k Bonus
# 15 30k Super Bonus
# 11 20k Drop Target
# 09 5x Treasure Saucer
# 03 Extra Ball Treasure Saucer
# 04 Saucer "A" (Right)
# 02 Special Treasure Saucer
# 10 Center "A" Right
# 18 Special Drop Target
# 13 Credit Indicator
# 14 8K golden cliff

lights:

# Bonus Section
  l_bonus_1k:
    number: 1-0-1-2
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_2k:
    number: 1-3-4-5
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_3k:
    number: 1-6-7-8
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_4k:
    number: 1-9-10-11
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_5k:
    number: 1-12-13-14
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_6k:
    number: 1-15-16-17
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_7k:
    number: 1-18-19-20
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_8k:
    number: 1-21-22-23
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_9k:
    number: 1-24-25-26
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_10k:
    number: 1-27-28-29
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Super Bonus Section
  l_bonus_super_20k:
    number: 1-30-31-32
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_super_30k:
    number: 1-33-34-35
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_super_40k:
    number: 1-36-37-38
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Multiplier Section
  l_bonus_2x:
    number: 1-39-40-41
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_3x:
    number: 1-42-43-44
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_5x:
    number: 1-45-46-47
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_bonus_shoot_again:
    number: 1-48-49-50
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Spinner Section
# Manual shows 4 controled lights but playfield appears to have 5
# Numbered from bottom up
  l_spinner_1:
    number: 1-51-52-53
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_spinner_2:
    number: 1-54-55-56
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_spinner_3:
    number: 1-57-58-59
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_spinner_4:
    number: 1-60-61-62
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_spinner_5:
    number: 1-63-64-65
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Golden Cliffs
  l_goldencliffs_2k:
    number: 1-66-67-68
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_goldencliffs_4k:
    number: 1-69-70-71
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_goldencliffs_6k:
    number: 1-72-73-74
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_goldencliffs_8k:
    number: 1-75-76-77
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_goldencliffs_10k:
    number: 1-78-79-80
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_goldencliffs_20k:
    number: 1-81-82-83
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Water Lane
  l_waterlane_5k:
    number: 2-0-1-2
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_waterlane_10k:
    number: 2-3-4-5
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_waterlane_special:
    number: 2-6-7-8
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Drop Target (Not In-Line)
  l_droptarget_10k:
    number: 2-9-10-11
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
# Drop Target (Not In-Line)
  l_droptarget_15k:
    number: 2-12-13-14
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
# Drop Target (Not In-Line)
  l_droptarget_20k:
    number: 2-15-16-17
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
# Drop Target (Not In-Line)
  l_droptarget_25k:
    number: 2-18-19-20
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
# Drop Target (Not In-Line)
  l_droptarget_special:
    number: 2-21-22-23
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Treasure Saucer
# Drop Target (Not In-Line)
  l_treasure_5x:
    number: 2-24-25-26
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_treasure_extra_ball:
    number: 2-27-28-29
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_treasure_special:
    number: 2-30-31-32
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Paragon Center
  l_paragon_center_01p:
    number: 2-33-34-35
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_center_02a:
    number: 2-36-37-38
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_center_03r:
    number: 2-39-40-41
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_center_04a:
    number: 2-42-43-44
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_center_05g:
    number: 2-45-46-47
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_center_06o:
    number: 2-48-49-50
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_center_07n:
    number: 2-51-52-53
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Paragon Saucer
  l_paragon_saucer_01p:
    number: 2-54-55-56
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_saucer_02a:
    number: 2-57-58-59
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_saucer_03r:
    number: 2-60-61-62
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_saucer_04a:
    number: 2-63-64-65
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_saucer_05g:
    number: 2-66-67-68
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_saucer_06o:
    number: 2-69-70-71
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_saucer_07n:
    number: 2-72-73-74
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_paragon_saucer_special:
    number: 2-75-76-77
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true

# Misc Informational Lights
  l_info_ball_in_play:
    number: 2-78-79-80
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_info_credit_indicator:
    number: 2-81-82-83
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_info_game_over:
    number: 3-0-1-2
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_info_high_score_to_date:
    number: 3-3-4-5
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_info_match:
    number: 3-6-7-8
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_info_same_player_sa:
    number: 3-9-10-11
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true
  l_info_tilt:
    number: 3-12-13-14
    subtype: led
    fade_ms: 50ms
    platform_settings:
      polarity: true