#config_version=5

#Machine level settings that will be available on the setup menu
#Eventually should split this up into Kodelia Common and Game Specific sections

# In other config files, refer to these using --
# settings.[setting name]

settings:
# STANDARD SETTINGS
  balls_per_game:
    label: Balls Per Game
    values:
      3: "3 (default)"
      4: "4"
      5: "5"
      6: "6"
      7: "7"
      8: "8"
      9: "9"
      10: "10" # jake setting
    default: 3
    key_type: int
    sort: 100
    settingType: standard

  max_players:
    label: Maximum Players
    values:
      1: "1"
      2: "2"
      4: "4 (default)"
    default: 4
    key_type: int
    sort: 110
    settingType: standard

  initial_ball_save:
    label: Initial Ball Save Time
    key_type: int
    default: 12
    sort: 120
    values:
      0: "None"
      3: "3 seconds"
      4: "4 seconds"
      5: "5 seconds"
      6: "6 seconds"
      7: "7 seconds"
      8: "8 seconds"
      9: "9 seconds"
      10: "10 seconds"
      11: "11 seconds"
      12: "12 seconds (default)"
      13: "13 seconds"
      14: "14 seconds"
      15: "15 seconds"
      16: "16 seconds"
      17: "17 seconds"
      18: "18 seconds"
      19: "19 seconds"
      20: "20 seconds"
      21: "21 seconds"
      22: "22 seconds"
      23: "23 seconds"
      24: "24 seconds"
      25: "25 seconds"
      26: "26 seconds"
      27: "27 seconds"
      28: "28 seconds"
      29: "29 seconds"
      30: "30 seconds"
    settingType: standard

# GAME SETTINGS
  hazzard_scoring:
    label: Hazzard Saucer Scoring
    values:
      0: "scores 500 and 1 bonus advance"
      1: "scores 3000 and 2 bonus advances (default)"
    default: 1
    key_type: int
    sort: 101
    settingType: game

  hazzard_scan:
    label: Hazzard Saucer Scanning
    values:
      0: "letters scan continuously"
      1: "letters advance one at a time (default)"
    default: 1
    key_type: int
    sort: 102
    settingType: game

  in_line_scoring:
    label: Inline Target Scoring
    values:
      0: "target scores 1000 and 1 bonus advance"
      1: "target scores 3000 and 2 bonus advances (default)"
    default: 1
    key_type: int
    sort: 103
    settingType: game

  in_line_spotting:
    label: Inline Target Spots
    values:
      0: "target does not spot Hazzard letter"
      1: "target spots Hazzard letter (default)"
    default: 1
    key_type: int
    sort: 104
    settingType: game

  waterfall_drops_special:
    label: Waterfall Drop Special
    values:
      0: "Special reverts after collected"
      1: "Special remains after collected (default)"
    default: 1
    key_type: int
    sort: 105
    settingType: game

  waterfall_lane_feature:
    label: Waterfall Lane Feature
    values:
      0: "1000 - 5000 - 10000 - Special - 10000"
      1: "5000 - 10000 - Special - 10000 (default)"
    default: 1
    key_type: int
    sort: 106
    settingType: game

  special_award:
    label: Special Award
    values:
      0: "No Award"
      1: "Replay"
      2: "Extra Ball"
      3: "25000/50000 Points (default)"
    default: 3
    key_type: int
    sort: 107
    settingType: game

# COIN SETTINGS
# Note that "Free Play/Coin Play" is a "default" setting provided by MPF and therefore not listed here
  maximum_credits:
    label: Maximum Credits
    values:
      10: "10"
      20: "20"
      30: "30 (default)"
      40: "40"
      50: "50"
      60: "60"
      99: "99"
    default: 30
    key_type: int
    sort: 200
    settingType: coin

  match_feature:
    label: Match Feature
    values:
      0: "Off"
      1: "On (default)"
    default: 1
    key_type: int
    sort: 210
    settingType: coin

# FEATURE settings
  inline_memory_feature:
    label: In-Line Drop Target Memory
    values:
      0: "Off"
      1: "On (default)"
    default: 1
    key_type: int
    sort: 90
    settingType: feature

  creek_multiball_feature:
    label: Creek Multiball Enabled
    values:
      0: "Off"
      1: "On (default)"
    default: 1
    key_type: int
    sort: 100
    settingType: feature

  creek_ball_save:
    label: Creek Multiball Ball Save Time
    key_type: int
    default: 15
    sort: 120
    values:
      0: "None"
      3: "3 seconds"
      4: "4 seconds"
      5: "5 seconds"
      6: "6 seconds"
      7: "7 seconds"
      8: "8 seconds"
      9: "9 seconds"
      10: "10 seconds"
      11: "11 seconds"
      12: "12 seconds"
      13: "13 seconds"
      14: "14 seconds"
      15: "15 seconds (default)"
      16: "16 seconds"
      17: "17 seconds"
      18: "18 seconds"
      19: "19 seconds"
      20: "20 seconds"
      21: "21 seconds"
      22: "22 seconds"
      23: "23 seconds"
      24: "24 seconds"
      25: "25 seconds"
      26: "26 seconds"
      27: "27 seconds"
      28: "28 seconds"
      29: "29 seconds"
      30: "30 seconds"
    settingType: feature

  hazzard_multiball_feature:
    label: Hazzard Multiball Enabled
    values:
      0: "Off"
      1: "On (default)"
    default: 1
    key_type: int
    sort: 110
    settingType: feature

  hazzard_ball_save:
    label: Hazzard Multiball Ball Save Time
    key_type: int
    default: 15
    sort: 120
    values:
      0: "None"
      3: "3 seconds"
      4: "4 seconds"
      5: "5 seconds"
      6: "6 seconds"
      7: "7 seconds"
      8: "8 seconds"
      9: "9 seconds"
      10: "10 seconds"
      11: "11 seconds"
      12: "12 seconds"
      13: "13 seconds"
      14: "14 seconds"
      15: "15 seconds (default)"
      16: "16 seconds"
      17: "17 seconds"
      18: "18 seconds"
      19: "19 seconds"
      20: "20 seconds"
      21: "21 seconds"
      22: "22 seconds"
      23: "23 seconds"
      24: "24 seconds"
      25: "25 seconds"
      26: "26 seconds"
      27: "27 seconds"
      28: "28 seconds"
      29: "29 seconds"
      30: "30 seconds"
    settingType: feature

  chase_multiball_feature:
    label: Chase Multiball Enabled
    values:
      0: "Off"
      1: "On (default)"
    default: 1
    key_type: int
    sort: 130
    settingType: feature

  chase_ball_save:
    label: Chase Multiball Ball Save Time
    key_type: int
    default: 15
    sort: 140
    values:
      0: "None"
      3: "3 seconds"
      4: "4 seconds"
      5: "5 seconds"
      6: "6 seconds"
      7: "7 seconds"
      8: "8 seconds"
      9: "9 seconds"
      10: "10 seconds"
      11: "11 seconds"
      12: "12 seconds"
      13: "13 seconds"
      14: "14 seconds"
      15: "15 seconds (default)"
      16: "16 seconds"
      17: "17 seconds"
      18: "18 seconds"
      19: "19 seconds"
      20: "20 seconds"
      21: "21 seconds"
      22: "22 seconds"
      23: "23 seconds"
      24: "24 seconds"
      25: "25 seconds"
      26: "26 seconds"
      27: "27 seconds"
      28: "28 seconds"
      29: "29 seconds"
      30: "30 seconds"
    settingType: feature