#config_version=5

sound_system:
  buffer: 2048
  channels: 1
  enabled: True
  frequency: 44100
  master_volume: 0.8
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: .6
    voice:
      type: standard
      simultaneous_sounds: 10
      volume: 0.8
    sfx:
      type: standard
      simultaneous_sounds: 32
      volume: 0.8

sounds:
  # Music
  bonuscountdownmusic:
    file: bonus_countdown.wav
    track: music
  doh_track0:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Menu Theme.wav"
    track: music
  doh_track1:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 1.wav"
    track: music
  doh_track2:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 2.wav"
    track: music
  doh_track3:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 3.wav"
    track: music
  doh_track4:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 4.wav"
    track: music
  doh_track5:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 5.wav"
    track: music
  doh_track6:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 6.wav"
    track: music
  doh_track7:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Credits.wav"
    track: music
  doh_theme:
    file: "Waylon Jennings - Dukes Of Hazzard 'Good Ol' Boys' Theme Song.wav"
    track: music
  chase_theme:
    file: "The Dukes of Hazzard Season 01 Chase Theme.wav"
    track: music
    volume: 1.0

  # SFX
  dirt_peel:
    file: dirt_peel.wav
    track: sfx
    simultaneous_limit: 1
    stealing_method: skip
  dixie_horn:
    file: dixie_horn.wav
    track: sfx
    simultaneous_limit: 1
    stealing_method: skip
  police_siren:
    file: police_siren.wav
    track: sfx
  idle:
    file: idle.wav
    track: sfx
    volume: 0.3
  rev_up:
    file: rev_up.wav
    track: sfx
    volume: 0.3
  launch_car:
    file: launch_car.wav
    track: sfx
    volume: 0.3
  car_door:
    file: car_door.wav
    track: sfx
  gunfire1:
    file: gunfire1.wav
    track: sfx
    volume: 0.6
  gunfire2:
    file: gunfire2.wav
    track: sfx
    volume: 0.6
  gunfire3:
    file: gunfire3.wav
    track: sfx
    volume: 0.6
  oil:
    file: oil.wav
    track: sfx
    volume: 0.8
    simultaneous_limit: 1
    stealing_method: skip
  creek:
    file: creek.wav
    track: sfx
    volume: 0.6
    simultaneous_limit: 1
    stealing_method: skip
  jail_door:
    file: jail_door.wav
    track: sfx
    volume: 0.6
    simultaneous_limit: 1
    stealing_method: oldest

  #Voice Clips
  ##Player Add Clips
  hi_fellas:
    file: hi_fellas.wav
    track: voice
  i_love_it:
    file: i_love_it.wav
    track: voice
  public_enemy_number_one:
    file: public_enemy_number_one.wav
    track: voice
  yall_got_your_ears_on:
    file: yall_got_your_ears_on.wav
    track: voice
  get_them_duke_boys:
    file: get_them_duke_boys.wav
    track: voice
  hello_sugar_plum:
    file: hello_sugar_plum.wav
    track: voice

  ##Multiplayer Add Clips
  gonna_kick_my_butt_is_he:
    file: gonna_kick_my_butt_is_he.wav
    track: voice
  its_them_again:
    file: its_them_again.wav
    track: voice
  join_us_pit_stop:
    file: join_us_pit_stop.wav
    track: voice

  ##Drain Clips
  howl:
    file: basset_howl.wav
    track: voice
  aint_our_day:
    file: aint_our_day.wav
    track: voice
  gonna_miss_sometime:
    file: gonna_miss_sometime.wav
    track: voice
  aint_doing_too_great:
    file: aint_doing_too_great.wav
    track: voice
  numbskull:
    file: numbskull.wav
    track: voice
  out_of_bed:
    file: out_of_bed.wav
    track: voice
  behind_bars_entertainment:
    file: behind_bars_entertainment.wav
    track: voice
  things_look_bad:
    file: things_look_bad.wav
    track: voice
  that_is_terrible:
    file: that_is_terrible.wav
    track: voice

## Ducking example
#  player_one_up:
#      file: first_player_up.wav
#      track: voice
#      ducking:
#        target: music
#        delay: 0ms
#        attack: 100ms
#        attenuation: .1
#        release_point: 1.7s
#        release: 500ms
#

sound_pools:
  player_1_add:
    type: random_force_all
    track: voice
    sounds:
      - hi_fellas
      - i_love_it
      - public_enemy_number_one
      - yall_got_your_ears_on
      - get_them_duke_boys
      - hello_sugar_plum
    simultaneous_limit: 1
    stealing_method: skip
  player_multi_add:
    type: random_force_all
    track: voice
    sounds:
      - gonna_kick_my_butt_is_he
      - its_them_again
      - join_us_pit_stop
    simultaneous_limit: 1
    stealing_method: skip
  gameplay_music:
    type: random_force_all
    track: music
    sounds:
      - doh_track0
      - doh_track1
      - doh_track2
      - doh_track3
      - doh_track4
      - doh_track5
      - doh_track6
      - doh_track7
  gunfire:
    type: random
    track: sfx
    sounds:
      - gunfire1
      - gunfire2
      - gunfire3
    simultaneous_limit: 5
    stealing_method: skip
  drain_clips:
    type: random_force_all
    track: voice
    sounds:
      - howl
      - aint_our_day
      - gonna_miss_sometime
      - aint_doing_too_great
      - numbskull
      - out_of_bed
      - behind_bars_entertainment
      - things_look_bad
      - that_is_terrible
