#config_version=5

sound_system:
  buffer: 2048
  channels: 1
  enabled: True
  frequency: 44100
  master_volume: 0.8
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: .6
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.85
    sfx:
      type: standard
      simultaneous_sounds: 32
      volume: 0.8

sounds:
  # Music
  bonuscountdownmusic:
    file: bonus_countdown.wav
    track: music
  doh_track0:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Menu Theme.wav"
    track: music
  doh_track1:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 1.wav"
    track: music
  doh_track2:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 2.wav"
    track: music
  doh_track3:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 3.wav"
    track: music
  doh_track4:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 4.wav"
    track: music
  doh_track5:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 5.wav"
    track: music
  doh_track6:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Track 6.wav"
    track: music
  doh_track7:
    file: "Dukes Of Hazzard - Racing For Home (PSX) OST - Credits.wav"
    track: music
  doh_theme:
    file: "Waylon Jennings - Dukes Of Hazzard 'Good Ol' Boys' Theme Song.wav"
    track: music
  chase_theme:
    file: "The Dukes of Hazzard Season 01 Chase Theme.wav"
    track: music
    volume: 1.0

  # SFX
  dirt_peel:
    file: dirt_peel.wav
    track: sfx
    simultaneous_limit: 1
    stealing_method: skip
  dixie_horn:
    file: dixie_horn.wav
    track: sfx
    simultaneous_limit: 1
    stealing_method: skip
  police_siren:
    file: police_siren.wav
    track: sfx
  idle:
    file: idle.wav
    track: sfx
    volume: 0.3
  rev_up:
    file: rev_up.wav
    track: sfx
    volume: 0.25
  launch_car:
    file: launch_car.wav
    track: sfx
    volume: 0.25
  car_door:
    file: car_door.wav
    track: sfx
    volume: 0.7
  gunfire1:
    file: gunfire1.wav
    track: sfx
    volume: 0.7
  gunfire2:
    file: gunfire2.wav
    track: sfx
    volume: 0.7
  gunfire3:
    file: gunfire3.wav
    track: sfx
    volume: 0.7
  oil:
    file: oil.wav
    track: sfx
    volume: 0.8
    simultaneous_limit: 1
    stealing_method: skip
  creek:
    file: creek.wav
    track: sfx
    volume: 0.45
    simultaneous_limit: 1
    stealing_method: skip
  jail_door:
    file: jail_door.wav
    track: sfx
    volume: 0.7
    simultaneous_limit: 1
    stealing_method: oldest
  ratchet:
    file: ratchet.wav
    track: sfx
    volume: 0.7
    simultaneous_limit: 3
    stealing_method: oldest
  explosion1:
    file: explosion1.wav
    track: sfx
    volume: 0.6
  explosion2:
    file: explosion2.wav
    track: sfx
    volume: 0.6
  explosion3:
    file: explosion3.wav
    track: sfx
    volume: 0.6


  #Voice Clips
  ##Player Add Clips
  hi_fellas:
    file: hi_fellas.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  i_love_it:
    file: i_love_it.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  public_enemy_number_one:
    file: public_enemy_number_one.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  yall_got_your_ears_on:
    file: yall_got_your_ears_on.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  get_them_duke_boys:
    file: get_them_duke_boys.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  hello_sugar_plum:
    file: hello_sugar_plum.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  ##Multiplayer Add Clips
  gonna_kick_my_butt_is_he:
    file: gonna_kick_my_butt_is_he.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  its_them_again:
    file: its_them_again.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  join_us_pit_stop:
    file: join_us_pit_stop.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  hazzard_competing:
    file: hazzard_competing.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  ##Drain Clips
  howl:
    file: basset_howl.wav
    track: voice
  aint_our_day:
    file: aint_our_day.wav
    track: voice
  gonna_miss_sometime:
    file: gonna_miss_sometime.wav
    track: voice
  aint_doing_too_great:
    file: aint_doing_too_great.wav
    track: voice
  numbskull:
    file: numbskull.wav
    track: voice
  out_of_bed:
    file: out_of_bed.wav
    track: voice
  behind_bars_entertainment:
    file: behind_bars_entertainment.wav
    track: voice
  things_look_bad:
    file: things_look_bad.wav
    track: voice
  that_is_terrible:
    file: that_is_terrible.wav
    track: voice

  ##Hazzard MB Clips
  derby_time:
    file: derby_time.wav
    track: voice
    stealing_method: oldest
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  air_force:
    file: air_force.wav
    track: voice
    stealing_method: oldest
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  ##Creek MB Clips
  nitrous_oxide:
    file: nitrous_oxide.wav
    track: voice
    stealing_method: oldest
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  jumped_that_crick:
    file: jumped_that_crick.wav
    track: voice
    stealing_method: oldest
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  ##Chase MB Clips
  were_gonna_bust_em:
    file: were_gonna_bust_em.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  rock_and_a_hard_place:
    file: rock_and_a_hard_place.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  gonna_get_em:
    file: gonna_get_em.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  duck_on_a_junebug:
    file: duck_on_a_junebug.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  hot_pursuit:
    file: hot_pursuit.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  never_could_catch_em:
    file: never_could_catch_em.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms


  ##Tilt CLips
  arrest_that_man:
    file: arrest_that_man.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  dishwater:
    file: dishwater.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  messed_up:
    file: messed_up.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  pea_pickin:
    file: pea_pickin.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  pompous:
    file: pompous.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  sensitivity:
    file: sensitivity.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  strike1_2_3:
    file: strike1_2_3.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  take_your_badge:
    file: take_your_badge.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  ##Tilt Warning Clips
  billy_blue_heck:
    file: billy_blue_heck.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  bodily_injury:
    file: bodily_injury.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  careful_with_that:
    file: careful_with_that.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  enough_of_that:
    file: enough_of_that.wav
    track: voice
  freeze:
    file: freeze.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  ##Attract Quips
  flapjacks:
    file: flapjacks.wav
    track: voice
  possum_gumbush:
    file: possum_gumbush.wav
    track: voice
  reflexes:
    file: reflexes.wav
    track: voice
  zinger:
    file: zinger.wav
    track: voice
  free_games:
    file: free_games.wav
    track: voice
  how_to_drive:
    file: how_to_drive.wav
    track: voice
  miss_you:
    file: miss_you.wav
    track: voice
  join_us:
    file: join_us.wav
    track: voice
  normal_day:
    file: normal_day.wav
    track: voice
  fit_right_in:
    file: fit_right_in.wav
    track: voice
  roscoes_dog_manners:
    file: roscoes_dog_manners.wav
    track: voice
  grits_from_gumdrops:
    file: grits_from_gumdrops.wav
    track: voice
  crazy_cooter:
    file: crazy_cooter.wav
    track: voice
  roscoe_p_coltrane:
    file: roscoe_p_coltrane.wav
    track: voice
  dunce:
    file: dunce.wav
    track: voice

  ##General Voice Clips
  jackpot:
    file: jackpot.wav
    track: voice
    stealing_method: oldest
    volume: 0.9
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  wrong_road:
    file: wrong_road.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  yee_haw:
    file: yee_haw.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  good_start:
    file: good_start.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  #Ball save voice clips
  they_gave_it_back:
    file: they_gave_it_back.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  no_arrest:
    file: no_arrest.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  thats_handy:
    file: thats_handy.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  killing_me:
    file: killing_me.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

  #Delay of launch voice clips
  move_it:
    file: move_it.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  long_time:
    file: long_time.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  get_outta_here:
    file: get_outta_here.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  where_are_you:
    file: where_are_you.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  wheres_enos:
    file: wheres_enos.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  hurry_up:
    file: hurry_up.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  dont_leave_me_hanging:
    file: dont_leave_me_hanging.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  quit_stallin:
    file: quit_stallin.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  do_something:
    file: do_something.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  dangit_where_are_you:
    file: dangit_where_are_you.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  get_on_with_it:
    file: get_on_with_it.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms
  dang_that_cooter:
    file: dang_that_cooter.wav
    track: voice
    ducking:
      target:
        - music
        - sfx
      attenuation: 0.2
      delay: 0ms
      attack: 100ms
      release_point: 100ms
      release: 100ms

sound_pools:
  player_1_add:
    type: random_force_all
    track: voice
    sounds:
      - hi_fellas
      - i_love_it
      - public_enemy_number_one
      - yall_got_your_ears_on
      - get_them_duke_boys
      - hello_sugar_plum
    simultaneous_limit: 1
    stealing_method: skip
  player_multi_add:
    type: random_force_all
    track: voice
    sounds:
      - gonna_kick_my_butt_is_he
      - its_them_again
      - join_us_pit_stop
      - hazzard_competing
    simultaneous_limit: 1
    stealing_method: skip
  gameplay_music:
    type: random_force_all
    track: music
    sounds:
      - doh_track0
      - doh_track1
      - doh_track2
      - doh_track3
      - doh_track4
      - doh_track5
      - doh_track6
      - doh_track7
  gunfire:
    type: random_force_all
    track: sfx
    sounds:
      - gunfire1
      - gunfire2
      - gunfire3
    simultaneous_limit: 5
    stealing_method: skip
  explosion:
    type: random_force_all
    track: sfx
    sounds:
      - explosion1
      - explosion2
      - explosion3
    simultaneous_limit: 3
    stealing_method: oldest
  drain_clips:
    type: random_force_all
    track: voice
    sounds:
      - howl
      - aint_our_day
      - gonna_miss_sometime
      - aint_doing_too_great
      - numbskull
      - out_of_bed
      - behind_bars_entertainment
      - things_look_bad
      - that_is_terrible
  tilt_sounds:
    type: random_force_all
    track: voice
    sounds:
      - arrest_that_man
      - dishwater
      - messed_up
      - pea_pickin
      - pompous
      - sensitivity
      - strike1_2_3
      - take_your_badge
  tilt_warning_sounds:
    type: random_force_all
    track: voice
    simultaneous_limit: 1
    stealing_method: skip
    sounds:
      - billy_blue_heck
      - bodily_injury
      - careful_with_that
      - enough_of_that
      - freeze
  attract_voice:
    type: random_force_all
    track: voice
    sounds:
      - flapjacks
      - possum_gumbush
      - reflexes
      - zinger
      - free_games
      - how_to_drive
      - miss_you
      - join_us
      - normal_day
      - fit_right_in
      - roscoes_dog_manners
      - grits_from_gumdrops
      - crazy_cooter
      - roscoe_p_coltrane
      - dunce
  jackpot_clips:
    type: random_force_all
    track: voice
    sounds:
      - jackpot
  ball_saves:
    type: random_force_all
    track: voice
    sounds:
      - they_gave_it_back
      - no_arrest
      - thats_handy
      - killing_me
  launch_delay:
    type: random_force_all
    track: voice
    sounds:
      - move_it
      - get_outta_here
      - where_are_you
      - wheres_enos
      - hurry_up
      - quit_stallin
      - do_something
      - get_on_with_it
  big_launch_delay:
    type: random_force_all
    track: voice
    sounds:
      - long_time
      - dang_that_cooter