#config_version=5

sound_system:
  buffer: 1024
  channels: 1
  enabled: True
  frequency: 44100
  master_volume: 0.75
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: .5
    voice:
      type: standard
      simultaneous_sounds: 10
      volume: 0.8
    sfx:
      type: standard
      simultaneous_sounds: 32
      volume: 0.8

sounds: 
  # Music
  bonuscountdownmusic:
    file: bonus_countdown.ogg
    track: music
  # SFX
  dirt_peel:
    file: dirt_peel.wav
    track: sfx
    simultaneous_limit: 1
    stealing_method: skip

  #Voice Clips
  ##Player Add Clips
  hi_fellas:
      file: hi_fellas.wav
      track: voice
  i_love_it:
      file: i_love_it.wav
      track: voice
  public_enemy_number_one:
      file: public_enemy_number_one.wav
      track: voice
  yall_got_your_ears_on:
      file: yall_got_your_ears_on.wav
      track: voice
  get_them_duke_boys:
      file: get_them_duke_boys.wav
      track: voice
  hello_sugar_plum:
      file: hello_sugar_plum.wav
      track: voice

  ##Multiplayer Add Clips
  gonna_kick_my_butt_is_he:
      file: gonna_kick_my_butt_is_he.wav
      track: voice
  its_them_again:
      file: its_them_again.wav
      track: voice
  join_us_pit_stop:
      file: join_us_pit_stop.wav
      track: voice

## Ducking example
#  player_one_up:
#      file: first_player_up.wav
#      track: voice
#      ducking:
#        target: music
#        delay: 0ms
#        attack: 100ms
#        attenuation: .1
#        release_point: 1.7s
#        release: 500ms
#

sound_pools:
  player_1_add:
    type: random_force_all
    track: voice
    sounds:
      - hi_fellas
      - i_love_it
      - public_enemy_number_one
      - yall_got_your_ears_on
      - get_them_duke_boys
      - hello_sugar_plum
    simultaneous_limit: 1
    stealing_method: skip
  player_multi_add:
    type: random_force_all
    track: voice
    sounds:
      - gonna_kick_my_butt_is_he
      - its_them_again
      - join_us_pit_stop
    simultaneous_limit: 1
    stealing_method: skip
