#config_version=5

# PARAGON Base Machine Switches
# 01 Drop target (inline) "D" (top)
# 02 Drop target (inline) "C"
# 03 Drop target (inline) "B"
# 04 Drop target (inline) "A"
# 05
# 06 Credit Button
# 07 Tilt (3)
# 08 Outhole
# 09 Coin III (Right)
# 10 Coin I (Left)
# 11 Coin II (middle)
# 12
# 13
# 14
# 15
# 16 Slam (2)
# 17 Drop Target "C" (bottom)
# 18 Drop Target "B"
# 19 Drop Target "A"
# 20
# 21
# 22 Right outline
# 23 Right flip feeder lane
# 24 Paragon saucer
# 25
# 26 Top center rollover button
# 27 500 point rebound (2)
# 28 Waterfall rollover button
# 29 Center target
# 30 Top center target
# 31 Treasure chamber saucer
# 32 Golden Cliffs saucer
# 33 Spinner
# 34 Top right, golden cliffs rollover button and drop target rebound
# 35 Right Slingshot
# 36 Left Slingshot
# 37 Bottom thumper bumper
# 38 Center thumper bumper
# 39 Right thumper bumper
# 40 Left thumper bumper

switches:
  # Inline Drop Targets (a = bottom, d = top)
  s_drop_inline_a:
    number: 0/0/0
  s_drop_inline_b:
    number: 0/0/1
  s_drop_inline_c:
    number: 0/0/2
  s_drop_inline_d:
    number: 0/0/3

  # Coindoor/Tilt
  s_credit_button:
    number: 0/0/4
    tags: start
    ignore_window_ms: 500
  s_tilt:
    number: 0/0/5
    tags: tilt_warning, playfield_active
  s_outhole:
    number: 0/0/6
  s_coin_1:
    number: 0/0/7
  s_coin_2:
    number: 0/1/0
  s_coin_3:
    number: 0/1/1
  s_slam:
    number: 0/1/2
  s_service_1:
    number: 2/0/2
  s_service_2:
    number: 2/0/3

  # Drop Targets - Right Side - C = Bottom
  s_drop_right_a:
    number: 0/1/3
  s_drop_right_b:
    number: 0/1/4
  s_drop_right_c:
    number: 0/1/5

  # Slingshots, Pops and Flippers
  s_flipper_left:
    number: 0/1/6
    tags: left_flipper
  s_flipper_right:
    number: 0/1/7
    tags: right_flipper
  s_slingshot_right:
    number: 1/0/0
  s_slingshot_left:
    number: 1/0/1
  s_thumper_bottom:
    number: 1/0/2
  s_thumper_center:
    number: 1/0/3
  s_thumper_right:
    number: 1/0/4
  s_thumper_left:
    number: 1/0/5

  # Saucers
  s_saucer_paragon:
    number: 1/0/6
    tags: playfield_active
  s_saucer_golden_cliffs:
    number: 1/0/7
    tags: playfield_active
  s_saucer_treasure_chamber:
    number: 1/1/0
    tags: playfield_active

  # Targets and Rebounds
  s_center_target:
    number: 1/1/1
    tags: playfield_active
  s_top_center_target:
    number: 1/1/2
    tags: playfield_active
  s_rebound_500pt:
    number: 1/1/3
    tags: playfield_active

  # Rollovers
  # Note that golden cliffs is also tied to drop rebound
  s_top_center_rollover:
    number: 1/1/4
    tags: playfield_active
  s_waterfall_rollover:
    number: 1/1/5
    tags: playfield_active
  s_golden_cliffs_rollover:
    number: 1/1/6
    tags: playfield_active

  # Uncategorized
  s_right_outlane:
    number: 1/1/7
    tags: playfield_active
  s_right_flip_feeder_lane:
    number: 2/0/0
    tags: playfield_active
  s_spinner:
    number: 2/0/1
    tags: playfield_active


