#config_version=5

# PARAGON Base Machine Switches
# 01 Drop target (inline) "D" (top)
# 02 Drop target (inline) "C"
# 03 Drop target (inline) "B"
# 04 Drop target (inline) "A"
# 05
# 06 Credit Button
# 07 Tilt (3)
# 08 Outhole
# 09 Coin III (Right)
# 10 Coin I (Left)
# 11 Coin II (middle)
# 12
# 13
# 14
# 15
# 16 Slam (2)
# 17 Drop Target "C" (bottom)
# 18 Drop Target "B"
# 19 Drop Target "A"
# 20
# 21
# 22 Right outline
# 23 Right flip feeder lane
# 24 Paragon saucer
# 25
# 26 Top center rollover button
# 27 500 point rebound (2)
# 28 Waterfall rollover button
# 29 Center target
# 30 Top center target
# 31 Treasure chamber saucer
# 32 Golden Cliffs saucer
# 33 Spinner
# 34 Top right, golden cliffs rollover button and drop target rebound
# 35 Right Slingshot
# 36 Left Slingshot
# 37 Bottom thumper bumper
# 38 Center thumper bumper
# 39 Right thumper bumper
# 40 Left thumper bumper

# Tag "KPF" is used to start the initial ball save timer.

switches:
  # Inline Drop Targets (a = bottom, d = top)
  s_drop_inline_a:
    number: 1-0-83
    tags: kpf, c_jack, h_jack, not_skill
  s_drop_inline_b:
    number: 1-0-84
    tags: kpf, c_jack, h_jack, not_skill
  s_drop_inline_c:
    number: 1-0-85
    tags: kpf, c_jack, h_jack, not_skill
  s_drop_inline_d:
    number: 1-0-86
    tags: kpf, c_jack, h_jack, not_skill

  # Coindoor/Tilt - these may change - assuming J2
  s_credit_button:
    number: 0-0-24
    tags: start
    ignore_window_ms: 250
  s_tilt:
    number: 0-0-25
    tags: tilt_warning
    ignore_window_ms: 2000ms
  s_service_0:  # back
    number: 0-0-18
    tags: service_esc
  s_service_1:
    number: 0-0-17
    tags: service_up
  s_service_2:
    number: 0-0-16
    tags: service_down
  s_service_3: # select
    number: 0-0-19
    tags: service_enter
  s_coin_1: # this wont exist
    number: 0-0-1
  s_coin_2: # this wont exist
    number: 0-0-2
  s_coin_3: # this wont exist
    number: 0-0-3

  s_flipper_left:
    number: 0-0-27
    tags: left_flipper
  s_flipper_right:
    number: 0-0-26
    tags: right_flipper

  # Optos - these may change - assuming J3
  s_trough_1:
    number: 0-0-11
    type: 'NC'
  s_trough_jam:
    number: 0-0-10
    type: 'NC'
  s_playfield_entry:
    number: 0-0-9
    tags: playfield_active

  # Drop Targets - Right Side - C = Bottom
  s_drop_right_a:
    number: 1-0-36
    tags: kpf, c_jack, h_jack, not_skill
  s_drop_right_b:
    number: 1-0-37
    tags: kpf, c_jack, h_jack, not_skill
  s_drop_right_c:
    number: 1-0-38
    tags: kpf, c_jack, h_jack, not_skill


  # Ball Control
  s_outhole:
    number: 1-0-80
#    tags: sw_early_ball_save
  s_trough_4:
    number: 1-0-40
  s_trough_3:
    number: 1-0-41
  s_trough_2:
    number: 1-0-42
  s_shooter_lane: #auto-plunge
    number: 1-0-34
    events_when_deactivated: shooter_lane_empty

  # Slingshots, Pops and Flippers

  s_slingshot_right:
    number: 1-0-51
    events_when_activated:
      - temp_sling_right
      - sling_sound
    tags: kpf, c_jack, h_jack, not_skill
  s_slingshot_left:
    number: 1-0-64
    events_when_activated:
      - temp_sling_left
      - sling_sound
    tags: kpf, c_jack, h_jack, not_skill
  s_thumper_bottom:
    number: 1-0-81
    events_when_activated: temp_thumper_bottom
    tags: kpf, c_jack, h_jack, not_skill
  s_thumper_center:
    number: 1-0-57
    events_when_activated: temp_thumper_center
    tags: kpf, c_jack, h_jack, not_skill
  s_thumper_right:
    number: 1-0-48
    events_when_activated: temp_thumper_right
    tags: kpf, c_jack, h_jack, not_skill
  s_thumper_left:
    number: 1-0-65
    events_when_activated: temp_thumper_left
    tags: kpf, c_jack, h_jack, not_skill
  #Temp switch to test mirror universe theory
  s_void:
    number: 1-0-72


  # Saucers
  s_saucer_paragon:
    number: 1-0-49
    tags: kpf, c_jack, not_skill
    ignore_window_ms: 500
  s_saucer_golden_cliffs:
    number: 1-0-66
    tags: kpf, h_jack
    ignore_window_ms: 500
  s_saucer_treasure_chamber:
    number: 1-0-87
    tags: kpf, c_jack, h_jack, not_skill
    ignore_window_ms: 500

  # Targets and Rebounds
  s_center_target:
    number: 1-0-56
    tags: kpf, c_jack, h_jack, not_skill
  s_top_center_target:
    number: 1-0-59
    tags: playfield_active, kpf, c_jack, h_jack, not_skill
  s_rebound_500pt:
    number: 1-0-75
    tags: kpf, c_jack, h_jack, not_skill
  s_left_mid_standup:
    number: 1-0-82
    tags: playfield_active, kpf, c_jack, h_jack, not_skill

  # Rollovers
  # Note that golden cliffs is also tied to drop rebound
  # SWITCH 34:
  s_top_center_rollover:
    number: 1-0-58
    tags: playfield_active, kpf, c_jack, h_jack
  s_waterfall_rollover:  # oil slick rollover
    number: 1-0-32
    tags: playfield_active, kpf, c_jack, h_jack, not_skill
  s_golden_cliffs_rollover:
    number: 1-0-67
    tags: playfield_active, kpf, c_jack, h_jack
  s_upper_right_rollver:
    number: 1-0-33
    tags: playfield_active, kpf, c_jack, h_jack, not_skill

  # Uncategorized
  s_right_outlane:
    number: 1-0-43
    tags: playfield_active, kpf, early_ball_save, c_jack, h_jack, not_skill
  s_right_flip_feeder_lane:
    number: 1-0-35
    tags: playfield_active, kpf, c_jack, h_jack, not_skill
  s_spinner:
    number: 1-0-74
    tags: playfield_active, kpf, c_jack, h_jack, not_skill
    debounce: quick
  s_right_drop_standing:
    number: 1-0-39
    tags: playfield_active, kpf, c_jack, h_jack, not_skill
