#config_version=5
switches:
  #Cabinet switches
  s_drain: #wired to left side controller
    number: 0/1/7
  s_start: #wired to right side controller
    number: 1/1/7
    tags: start
    ignore_window_ms: 500

  #Left side switches
  s_flipper_left:
    number: 0/0/0
    tags: left_flipper
  s_slingshot_left:
    number: 0/0/1
#    tags: playfield_active
  s_sTargetLowL:
    number: 0/0/2
    tags: playfield_active
  s_sTargetDropL:
    number: 0/0/3
    tags: playfield_active
  s_dTargetL0:
    number: 0/0/4
    ignore_window_ms: 250
#    tags: playfield_active
  s_dTargetL1:
    number: 0/0/5
    ignore_window_ms: 250
#    tags: playfield_active
  s_dTargetL2:
    number: 0/0/6
    ignore_window_ms: 250
#    tags: playfield_active
  s_dTargetL3:
    number: 0/0/7
    ignore_window_ms: 250
#    tags: playfield_active
  s_rooutlaneleft:
    number: 0/1/0
    tags: playfield_active
  s_roInLaneLeft:
    number: 0/1/1
    tags: playfield_active
  s_sTargetYellowL:
    number: 0/1/2
    tags: playfield_active
  s_sTargetUpperL:
    number: 0/1/3
    tags: playfield_active
  s_ir_scoop_detect:
    number: 0/1/4
    type: NC
    ignore_window_ms: 1000
# NOT YET IMPLEMENTED IN HARDWARE
# PLAYFIELD ACTIVE is needed or a tilt before hitting a switch will pop the ball back out after a drain
# TODO: see if there is a way to disable tilt detect prior to playfield validation
  s_tilt_bob:
    number: 0/1/5
    tags: tilt_warning, playfield_active


  #Right side switches
  s_flipper_right:
    number: 1/0/0
    tags: right_flipper
  s_slingshot_right:
    number: 1/0/1
#    tags: playfield_active
  s_sTargetLowR:
    number: 1/0/2
    tags: playfield_active
  s_sTargetDropR:
    number: 1/0/3
    tags: playfield_active
  s_dTargetR0:
    number: 1/0/4
    ignore_window_ms: 250
#    tags: playfield_active
  s_dTargetR1:
    number: 1/0/5
    ignore_window_ms: 250
#    tags: playfield_active
  s_dTargetR2:
    number: 1/0/6
    ignore_window_ms: 250
#    tags: playfield_active
  s_dTargetR3:
    number: 1/0/7
    ignore_window_ms: 250
#    tags: playfield_active
  s_rooutlaneright:
    number: 1/1/0
    tags: playfield_active
  s_roInLaneRight:
    number: 1/1/1
    tags: playfield_active
  s_sTargetYellowR:
    number: 1/1/2
    tags: playfield_active
  s_sTargetUpperR:
    number: 1/1/3
    tags: playfield_active
  s_spinner:
    number: 1/1/4
    tags: playfield_active

  #Upper and center switches
  s_lane0:
    number: 2/0/0
#    tags: playfield_active
  s_lane1:
    number: 2/0/1
    tags: playfield_active
  s_lane2:
    number: 2/0/2
    tags: playfield_active
  s_lane3:
    number: 2/0/3
    tags: playfield_active
  s_lane4:
    number: 2/0/4
# testing -- don't make this validate playfield due to playfield curves
#    tags: playfield_active
  s_jet_upper_left:
    number: 2/1/0
#    tags: playfield_active
  s_jet_lower_center:
    number: 2/1/1
#    tags: playfield_active
  s_jet_upper_right:
    number: 2/1/2
#    tags: playfield_active
  s_dtargetcl:
    number: 2/1/4
    ignore_window_ms: 250
#    tags: playfield_active
  s_dtargetcr:
    number: 2/1/3
    ignore_window_ms: 250
#    tags: playfield_active
  s_credit: #wired to upper/center controller
    number: 2/1/7