#config_version=5

mode:
  start_events: ball_started
  priority: 15

event_player:
  game_start:
    display_set_color|10ms:

segment_display_player:
  # init displays on game start
  game_start:
    display1:
      text: ""
    display2:
      text: ""
    display3:
      text: ""
    display4:
      text: ""
    display5:
      text: "{current_player.ball:d}"
  display_set_color:
    display1:
      action: set_color
      color: "FFA500"
    display2:
      action: set_color
      color: "FFA500"
    display3:
      action: set_color
      color: "FFA500"
    display4:
      action: set_color
      color: "FFA500"
  #    color: "776300"
    display5:
      action: set_color
      color: "FFA500"
  # show score when adding players
  player_added.1{num==1}:
    display1:
      text: "{players[0].score:d}"
      priority: 10
  player_added.2{num==2}:
    display2:
      text: "{players[1].score:d}"
      priority: 10
  player_added.3{num==3}:
    display3:
      text: "{players[2].score:d}"
      priority: 10
  player_added.4{num==4}:
    display4:
      text: "{players[3].score:d}"
      priority: 10

  player_turn_started.1{number==1}:
    display1:
      action: flash
  player_turn_ended.2{number==1}:
    display1:
      action: no_flash
  player_turn_started.3{number==2}:
    display2:
      action: flash
  player_turn_ended.4{number==2}:
    display2:
      action: no_flash
  player_turn_started.5{number==3}:
    display3:
      action: flash
  player_turn_ended.6{number==3}:
    display3:
      action: no_flash
  player_turn_started.7{number==4}:
    display4:
      action: flash
  player_turn_ended.8{number==4}:
    display4:
      action: no_flash

