#config_version=5

# Contains configuration data for the golden cliffs saucer

# Based on PARAGON Rules --
#
# Each hit of the golden cliffs saucer scores current value and advances to next value, does not reset per ball
#
#TODO -- play a show when hit, then eject the ball

mode:
  start_events: ball_started
  events_when_started: enable_base_creek_shot
  priority: 121

shot_profiles:
  creek:
    advance_on_hit: true
    states:
      - name: 2k
        show: creek2k
      - name: 4k
        show: creek4k
      - name: 6k
        show: creek6k
      - name: 8k
        show: creek8k
      - name: 10k
        show: creek10k
      - name: 20k
        show: creek20k

shots:
  creek_saucer:
    switch: s_saucer_golden_cliffs
    profile: creek
    disable_events: disable_base_creek_shot, disable_two_ball_multiball_progress
    enable_events: enable_base_creek_shot, enable_two_ball_multiball_progress
    reset_events: multiball_creek_multiball_ended

variable_player:
   creek_saucer_2k_hit:
     last_creek_value:
       int: 2000
       action: set
   creek_saucer_4k_hit:
     last_creek_value:
       int: 4000
       action: set
   creek_saucer_6k_hit:
     last_creek_value:
       int: 6000
       action: set
   creek_saucer_8k_hit:
     last_creek_value:
       int: 8000
       action: set
   creek_saucer_10k_hit:
     last_creek_value:
       int: 10000
       action: set
   creek_saucer_20k_hit:
     last_creek_value:
       int: 20000
       action: set
     bonuscount: 1
   player_last_creek_value:
     score:
       int: (value)
   multiball_creek_multiball_ended:
     creek_jackpot_count:
       action: set
       int: 0

event_player:
  creek_saucer_20k_hit{settings.creek_multiball_feature==1}:
    - start_mode_creek_multiball
  creek_saucer_20k_hit{current_player.last_creek_value==20000}:
    player_last_creek_value:
      value: 20000
      player_num:
        value: game.player.number
        type: int
  player_last_creek_value{player_num==game.player.number}:
    show_score_flash_text:
      text_1: "CREEK  "
      text_2: "VALUE"
      text_3: "SCORES "
      text_4:
        value: current_player.last_creek_value
        type: int
      events_when_completed: show_creek_score_done

ball_holds:
   bh_creek:
     balls_to_hold: 1
     hold_devices: bd_river_saucer
     release_one_events: show_creek_score_done, boars_nest_early_creek_entry
     enable_events: enable_base_creek_shot, multiball_creek_multiball_ended
     disable_events: disable_base_creek_shot

