#config_version=6

# Contains configuration data for the pop bumpers

# THIS IS A GUESS AND WILL LIKELY NEED TO BE REDONE
#
# Regular pops -- +10 points
# "Jail" (beast lair) -- -10 points

#TODO -- verify paragon pop rules

mode:
  start_events: ball_started
  events_when_started: reset_pop_count
  priority: 130

variable_player:
  s_thumper_bottom_active{current_player.score>current_player.pop_count*10}:
    score:
      action: add
      int: -10 * current_player.pop_count
    pop_count:
      action: add
      int: 1
  s_thumper_center_active:
    score: 10 * current_player.pop_count
    pop_count:
      action: add
      int: 1
  s_thumper_right_active:
    score: 10 * current_player.pop_count
    pop_count:
      action: add
      int: 1
  s_thumper_left_active:
    score: 10 * current_player.pop_count
    pop_count:
      action: add
      int: 1
  reset_pop_count:
    pop_count:
      action: set
      int: 1

