#config_version=5

mode:
  start_events: ball_ending
  stop_events: end_bonus
  priority: 5000
  use_wait_queue: true
  events_when_started: start_drain_show

event_player:
  start_bonus_countdown:
    - decrement_bonus|250ms
  player_bonuscount{value>0}:
    - decrement_bonus|500ms
  player_bonuscount{value==0}:
    - end_bonus

variable_player:
  decrement_bonus:
    bonuscount:
      action: add
      int: -1
    score:
      action: add
      int: 1000 * current_player.bonusmulti

show_player:
  player_bonuscount{value==39}:
    disable_40k:
      key: bonus_countdown
  player_bonuscount{value==29}:
    disable_30k:
      key: bonus_countdown
  player_bonuscount{value==19}:
    disable_20k:
      key: bonus_countdown
  start_drain_show{mode.tilt.tilt_warnings_remaining == 0}:
    drain_show:
      key: drain_show
      speed: 30
      loops: 0

sound_player:
  start_drain_show:
    #TODO Stopping the doh_theme here temporarily. Later it will be stopped by boar's nest mode end.
    doh_theme:
      action: stop
      fade_out: 500ms
    gameplay_music:
      action: stop
      fade_out: 500ms
  start_drain_show{mode.tilt.tilt_warnings_remaining == 0}:
    drain_clips:
      action: play
      loops: 0
      events_when_about_to_finish: start_bonus_countdown
      about_to_finish_time: 500ms
  start_bonus_countdown:
    bonuscountdownmusic:
      action: play
      loops: -1
  end_bonus:
    bonuscountdownmusic:
      action: stop
      fade_out: 500ms