#config_version=5

mode:
  file_log: full

event_player:
  player_score{player_num==1}:
    update_display_1:
#      text: current_player.score           DOES NOT WORK - DISPLAYS LITERAL
#      text: {value: players[0].score}      DOES NOT WORK - CRASHES MPF
#      text: (players[0].score)             DOES NOT WORK - DISPLAYS LITERAL
#      text: {players[0].score}             DOES NOT WORK - CRASHES MPF
#      text: {value: players(0).score}      DOES NOT WORK - CRASHES MPF
#      text: {value: players{0}.score}      DOES NOT WORK - CRASHES MPF
      text: {value: current_player.score}
#      text: {value: machine.game.player.score} DOES NOT WORK - CRASHES MPF
  player_score{player_num==2}:
    update_display_2:
      text: {value: current_player.score}
  player_score{player_num==3}:
    update_display_3:
      text: {value: current_player.score}
  player_score{player_num==4}:
    update_display_4:
      text: {value: current_player.score}


#slide_player:
#  game_started:
#     segment_displays:
#       priority: 20
#  game_ending:
#     segment_displays:
#         action: remove
#
#show_player:
#  game_started:
#     display_segment_displays:
#         action: stop
#slides:
#  segment_displays:
#    widgets:
#              - type: text
##                text: (player1|score)
#                text: (player1|score)
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 420
#                y: 624
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: (player2|score)
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 624
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: (player3|score)
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 420
#                y: 224
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: (player4|score)
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 224
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2
#              - type: text
#                text: "__00_00"
#                number_grouping: false
#                min_digits: 2
#                font_name: DSEG14Classic-Italic
#                color: orange
#                x: 820
#                y: 424
#                font_size: 40
#                anchor_x: right
#                anchor_y: bottom
#                z: 2

widget_player:
#  player_added{num==1}:
#    player_1_only:
#      slide: score_display_slide
#  player_added{num==2}:
#    player_1_only:
#      slide: score_display_slide
#      action: remove
#    player_1:
#      slide: score_display_slide
#    player_2:
#      slide: score_display_slide
#  player_added{num==3}:
#    player_3:
#      slide: score_display_slide
#  player_added{num==4}:
#    player_4:
#      slide: score_display_slide

widgets:
#  player_1_only:
#        - type: text
#          text: (score)
#          number_grouping: true
#          min_digits: 2
#          font_name: Ten_segment
#          color: orange
#          font_size: 24
#          anchor_y: top
#          anchor_x: top
#          x: 100
#          y: 550
#  player_1:
#        - type: text
#          text: (player1|score)
#          number_grouping: true
#          min_digits: 2
#          font_name: Ten_segment
#          color: orange
#          font_size: 24
#          anchor_y: top
#          anchor_x: top
#          x: 100
#          y: 550
#  player_2:
#        - type: text
#          text: (player2|score)
#          number_grouping: true
#          min_digits: 2
#          font_name: Ten_segment
#          color: orange
#          font_size: 24
#          anchor_y: top
#          anchor_x: top
#          x: 100
#          y: 450
#  player_3:
#        - type: text
#          text: (player3|score)
#          number_grouping: true
#          min_digits: 2
#          font_name: Ten_segment
#          color: orange
#          font_size: 24
#          anchor_y: top
#          anchor_x: top
#          x: 100
#          y: 350
#  player_4:
#        - type: text
#          text: (player4|score)
#          number_grouping: true
#          min_digits: 2
#          font_name: Ten_segment
#          color: orange
#          font_size: 24
#          anchor_y: top
#          anchor_x: top
#          x: 100
#          y: 250

